Wiremill Circuit Recipes
GregTechCEu/GregTechCEu-1.19 pull request #1004
Opened 2024-03-24 11:13 UTC by ReclipseTheOne

Nothing should be broken (copium)

2024-03-24 11:16 UTC, mikerooni approved these changes

2024-03-24 11:18 UTC, mikerooni commented
Looks good so far, should be able to include this in the next release after 1.1.4

2024-03-24 12:52 UTC, screret requested changes

2024-03-24 12:52 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/WireRecipeHandler.java
> +                .duration((int) material.getMass() * 3)
1.12 had a loop for this yk?

2024-03-24 12:52 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/WireRecipeHandler.java
> +                .duration((int) material.getMass() * 3)
would be cleaner :)

2024-03-24 12:52 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/WireRecipeHandler.java
> +                .duration((int) material.getMass() * 3)
https://github.com/GregTechCEu/GregTech/blob/master/src/main/java/gregtech/loaders/recipe/handlers/WireRecipeHandler.java#L86-L95

2024-03-27 06:21 UTC, screret approved these changes

2024-03-27 06:22 UTC, merged