Fix that kinetic stress output will never not stop
GregTechCEu/GregTechCEu-1.19 pull request #1110
Opened 2024-04-14 17:04 UTC by iamSmallY

Fix #1109 
The `preWorking` and `postWorking` is not called when the machine paused or destroyed.

2024-04-14 17:32 UTC, screret requested changes

2024-04-14 17:32 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeLogic.java
> +            lastRecipe.postWorking(machine);
what if `newStatus == Status.WAITING`? then the machine will do recipe completed actions whilst it's just out of energy.

2024-04-14 17:32 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeLogic.java
> +            lastRecipe.postWorking(machine);
other cases like this exist as well.

2024-04-14 17:32 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeLogic.java
> +            lastRecipe.preWorking(machine);
ditto

2024-04-16 12:15 UTC, iamSmallY commented
I rechecked the code logic and found that I could make changes in KineticPartMachine to fix this bug without modifying RecipeLogic. But now there is a problem that the stress output cannot be stopped when the controller is paused.

2024-04-16 13:24 UTC, screret commented
you could add a callback for that maybe?

2024-04-16 14:29 UTC, iamSmallY commented
I think now it will not have an excessive impact on the existing code logic.

2024-04-17 13:53 UTC, screret requested changes
I didn't say "do a second always-ticking thing to check it"
I said "add a callback for when the machine is paused in the recipe logic, and use it here to pause the hatch."

2024-04-17 13:53 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/part/KineticPartMachine.java
> +                    assert stopWorkingSub != null;
...this will literally just crash if the subscription happens to be null, for example by the loop already succeeding.

2024-04-18 05:28 UTC, iamSmallY commented
I didn't know how to add the callback so I used a `TickableSubscription`. Do you think it is appropriate to call each part's setWorkingEnabled in `WorkableMultiblockMachine`?

2024-04-18 05:39 UTC, screret commented
Well, look at what the onWorking/onWaiting etc. Methods do and apply that to this issue by adding an `onPaused`

2024-04-19 09:53 UTC, screret requested changes

2024-04-19 09:53 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/machine/feature/multiblock/IMultiPart.java
> +    default boolean onPaused(IWorkableMultiController controller) { return true; }
please format it correctly.

2024-04-19 10:33 UTC, iamSmallY commented
Sorry, my IDE displays other method as one line.

2024-04-19 12:44 UTC, screret approved these changes

2024-04-20 08:54 UTC, merged