Change "L/t" to "mb/t" for consistency
GregTechCEu/GregTechCEu-1.19 pull request #1379
Opened 2024-06-05 12:02 UTC by 3x1t-5tyl3

## What
#1378 

## Implementation Details
None. It only changes certain comments and lang files as-well as top and jade compat to show mb/t instead of L/t

## Outcome
See above.

## Additional Information
None.

## Potential Compatibility Issues
None.

2024-06-05 12:49 UTC, screret commented
It should be "mB", not "mb"

2024-06-05 13:40 UTC, 3x1t-5tyl3 commented
> It should be "mB", not "mb"

Whoops. Copy paste fail. I'll fix that.

2024-06-06 06:01 UTC, YoungOnionMC approved these changes

2024-06-06 10:25 UTC, screret commented
please run the `spotlessApply` task in your IDE.

2024-06-06 10:26 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/lang/LangHandler.java
> +        // Not sure if the Liter is still wanted? I'll keep these as Liter given they're named properly
do change them.

2024-06-06 20:56 UTC, screret requested changes

2024-06-06 20:56 UTC, screret commented on src/generated/resources/assets/gtceu/lang/en_ud.json
> +  "gtceu.machine.hpca.component_type.cooler_active_coolant": "%s ʇ/qɯ %dɟ§ :oʇ dn sǝɹınbǝᴚɔ§",
rerun datagen please.

2024-06-07 11:31 UTC, screret approved these changes

2024-06-07 12:11 UTC, screret approved these changes

2024-06-07 12:11 UTC, merged