pollution fixes
GregTechCEu/GregTechCEu-1.19 pull request #1417
Opened 2024-06-14 13:36 UTC by screret

## What
removes the client lag caused by pollution by reducing particle count and instead making larger particles.
also makes singleblock generators output very low amounts of pollution and makes the strength be stored as a float so smaller amounts can be output at a time.

## Implementation Details
new particle type that's like the basalt delta particle but colorable

## Outcome
less laggy environmental hazards

2024-06-14 14:03 UTC, 300f20t commented
It would be nice if this fix increased the maximum pollution limit, as it is too small.
![2024-06-14_14 04 43](https://github.com/GregTechCEu/GregTech-Modern/assets/93136063/15bb837c-a662-429c-9761-7f30462b2280)

2024-06-14 19:00 UTC, screret commented
> It would be nice if this fix increased the maximum pollution limit, as it is too small.

what?

2024-06-14 19:27 UTC, 300f20t commented
The pollution is too large and when transferring from the old version of GTm it becomes maximum and because of this it becomes impossible to play after 2-3 minutes of being on the base. Maybe I should have opened the issue.

2024-06-14 19:28 UTC, screret commented
that's... what this fixes.

2024-06-14 19:31 UTC, 300f20t commented
The fact that the maximum pm is 1000 is a pretty bad decision. In GT5, this value was several million.

2024-06-14 19:32 UTC, screret commented
it's not a maximum, it's the value at which it'll start spreading to chunks around it.

2024-06-14 19:32 UTC, screret commented
also this is not that close to GT5 pollution and smaller amounts are much more deadly

2024-06-14 19:34 UTC, 300f20t commented
It behaves very strangely and does not rise above 1000, but does not spread to other chunks.

2024-06-14 19:35 UTC, screret commented
have you tried the attached development build?
[build output.zip](https://github.com/GregTechCEu/GregTech-Modern/actions/runs/9519977572/artifacts/1603007866)

2024-06-14 19:37 UTC, 300f20t commented
I didn't want to create a issue because I couldn't reproduce the bug.

2024-06-14 19:42 UTC, 300f20t commented
![image](https://github.com/GregTechCEu/GregTech-Modern/assets/93136063/6d6286ed-e617-4c0e-8bc1-0e8810805d2e)

2024-06-14 19:43 UTC, 300f20t commented
I'm not sure, but it seems to have worked.

2024-06-14 19:50 UTC, 300f20t commented
I couldn't find any information about the pollution other than your commits on Github. Does the modification include any means of removing pollution?

2024-06-14 19:57 UTC, screret commented
that already exists, it's called the Air Scrubber.

2024-06-17 20:02 UTC, mikerooni requested changes

2024-06-17 20:02 UTC, mikerooni commented on src/main/java/com/gregtechceu/gtceu/client/EnvironmentalHazardClientHandler.java
> +        }
this part should probably be its own method as it's repeated a couple times above

2024-06-17 20:02 UTC, mikerooni commented on src/main/java/com/gregtechceu/gtceu/client/EnvironmentalHazardClientHandler.java
> +        return color;
the same goes for this part

2024-06-19 18:31 UTC, mikerooni approved these changes

2024-06-19 19:13 UTC, merged