Charcoal Pile Igniter
GregTechCEu/GregTechCEu-1.19 pull request #1493
Opened 2024-06-26 10:14 UTC by YoungOnionMC

Ever wanted charcoal quick and easier than a coke oven?

2024-07-06 19:51 UTC, screret requested changes

2024-07-06 19:51 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/block/BrittleCharcoalBlock.java
> +public class BrittleCharcoalBlock extends Block {
delete this empty class

2024-07-06 19:51 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/GTItems.java
> +                            x.getFluid() == GTMaterials.Propane.getFluid()),
use tags instead of hardcoding for GT fluids.

2024-07-06 19:51 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/item/tool/behavior/LighterBehavior.java
> +    }
look at what flint&steel does for rightclick?

2024-07-06 19:51 UTC, screret commented on src/main/resources/assets/gtceu/models/item/matchbox.json
why'd you hardcode the simple models?

2024-07-08 17:22 UTC, screret requested changes

2024-07-08 17:22 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/item/tool/behavior/LighterBehavior.java
> +    }
doesn't look resolved to me?

2024-07-10 08:41 UTC, screret submitted a review, later dismissed

2024-07-10 08:41 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/item/component/ThermalFluidStats.java
> +    }
Why not just make a new class?

2024-07-10 08:41 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/tags/ItemTagLoader.java
> +
Random line addition?

2024-07-10 08:41 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/core/mixins/CreeperMixin.java
> +    @Inject(method="mobInteract", at=@At(value = "HEAD"))
Formatting

2024-07-14 18:47 UTC, mikerooni approved these changes
Partial review for commits 290c4ca1e51484f8a4745cb9f210f0426d028ab0..09f6d2c38669b4fe6e19522d92a5d1ae743cb891 (the ones after @screret's previous review)

2024-07-14 18:58 UTC, mikerooni approved these changes

2024-07-14 19:19 UTC, merged