Food Behavior
GregTechCEu/GregTechCEu-1.19 pull request #1603
Opened 2024-07-22 09:33 UTC by qwer523

## What
Simple food behavior

## Additional Information
I like food (delight

2024-07-24 18:13 UTC, screret requested changes

2024-07-24 18:13 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/item/component/IComponentCapability.java
lets not move this

2024-07-25 06:23 UTC, qwer523 commented
Strangely, the failed check seems to be due to network issues, and I have tried again several times.

2024-07-25 17:58 UTC, screret approved these changes

2024-07-26 07:27 UTC, merged