Update zh_tw.json
GregTechCEu/GregTechCEu-1.19 pull request #1605
Opened 2024-07-22 11:59 UTC by IamNotBrianZ

## What
Update zh_tw.json

2024-07-22 12:11 UTC, Chococar-NSW requested changes
只有一個小問題

2024-07-22 18:09 UTC, IamNotBrianZ commented
> 只有一個小問題

不好意思，是什麼問題，我沒看到你標在哪?

2024-07-23 04:05 UTC, Chococar-NSW commented
https://github.com/GregTechCEu/GregTech-Modern/pull/1605#pullrequestreview-2191407211

2024-07-23 04:31 UTC, IamNotBrianZ commented
你留下的link從我這裡看是又連回這一頁
不如你直接說哪裡有錯，我就直接改
![螢幕擷取畫面 2024-07-23 122703](https://github.com/user-attachments/assets/b25cc530-4dad-4caf-b041-ab0b0f9115ce)

我真的看不到你的review

2024-07-23 04:37 UTC, Chococar-NSW commented
我傳DC好了

2024-07-23 04:54 UTC, Chococar-NSW approved these changes

2024-07-23 04:54 UTC, Chococar-NSW commented on src/main/resources/assets/gtceu/lang/zh_tw.json
> +    "tile.gtceu.brittle_charcoal.tooltip.1":"破壞可掉落木炭。",
原文是Mine 所以我覺得破壞不適合用在這裡

2024-07-26 07:36 UTC, screret approved these changes

2024-07-26 07:36 UTC, merged