RecipeBuilder and Kube methods for ranged item amounts
GregTechCEu/GregTechCEu-1.19 pull request #1645
Opened 2024-08-05 05:36 UTC by YoungOnionMC

2024-08-05 19:04 UTC, screret reviewed
where is the input logic you said you'd add?

2024-08-05 19:24 UTC, YoungOnionMC commented
> where is the input logic you said you'd add?

Are you able to write it in on this pr

2024-08-05 19:26 UTC, screret commented
can't approve it if I do that

2024-08-07 18:41 UTC, screret requested changes

2024-08-07 18:41 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +    }
remove these (they don't work, how would they even work?)

2024-08-08 05:41 UTC, screret approved these changes

2024-08-08 05:41 UTC, merged