Machine Ownership
GregTechCEu/GregTechCEu-1.19 pull request #1689
Opened 2024-08-10 10:31 UTC by YoungOnionMC

## What
Gives machines owners with UUIDs

## Implementation Details
any new machine placed will capture what placed it(just players for now) and set it as its owner

## Outcome
Potential future use for various things like wireless api, machine locking, etc

## Additional Information
could be expanded for compatibility for ftb teams

## Potential Compatibility Issues
any machine placed before this pr will have a null owner, but you can just break and replace it

2024-08-10 15:17 UTC, screret requested changes

2024-08-10 15:17 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/blockentity/MetaMachineBlockEntity.java
> +        return ServerLifecycleHooks.getCurrentServer().getPlayerList().getPlayerByName(ownerName) != null;
don't do this, get the owner by UUID instead.

2024-08-10 15:17 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/blockentity/KineticMachineBlockEntity.java
> +        return null;
implement the same things you did in MetaMachineBlockEntity here.

2024-08-10 15:17 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/item/PortableScannerBehavior.java
> +                    list.add(Component.translatable("behavior.portable_scanner.machine_ownership", mmBE.getOwnerName(),
why not just make these methods part of the IMachineBlockEntity interface?

2024-08-11 05:17 UTC, Ghostipedia requested changes
Make sure to natively support some kind of teams interface before this gets merged rather than doing it after.
Most common teams mod is FTBTeams & Argonauts, we should at a bear minimum find out how their team data is stored and also assign that as well if the player is in a team. 
Not having this in the initial API will result in addondevs not natively providing support either and cause more technical debt across the board than getting it done now.

2024-08-11 08:58 UTC, screret requested changes
also add Argonauts support

2024-08-11 08:58 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/blockentity/MetaMachineBlockEntity.java
> +    }
use `@Getter` for this

2024-08-11 08:58 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/blockentity/MetaMachineBlockEntity.java
> +    }
use `@Getter` for this

2024-08-11 08:58 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/blockentity/KineticMachineBlockEntity.java
> +    }
use `@Getter` for this

2024-08-11 08:58 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/blockentity/KineticMachineBlockEntity.java
>      }
use `@Getter` for this

2024-09-01 07:57 UTC, screret commented
actually, this can't store the *team* as the owner anyway, since people can change teams. it should instead check if the using player and the owner are in the same team, I guess?

2024-09-17 02:44 UTC, closed without merging