ME Pattern Buffer (Gregic Energistics ME IO Buffer CEU Port)
GregTechCEu/GregTechCEu-1.19 pull request #1737
Opened 2024-08-16 09:41 UTC by Ghostipedia

Before Anyone asks, yes permission to use GE code was granted, I feel we should still give credit in the readme to Qwer and the EpimorphicPioneers Team for some of the great work they've done so far, even if permission was granted.
![image](https://github.com/user-attachments/assets/e4376584-e512-4345-9784-1fccbb1c2f1a)

Currently still working through it, this PR will server as yet another "Ghost needs a checklist or they will forget" thing, as well as let people view my (arguably awful) porting skills :tr: 

TODO : 
- [ ] Get the Game to load
- [ ] Get the Actual block to exist
- [ ] Functionality from GE ported
- [ ] Removal of Uneeded behaviors and or Feature Rebalancing (Auto-output back from itself, others TBD)
- [ ] Proper Textures for UI, Overlay, and Hull/casing Render
- [ ] Lang, so much lang
- [ ] IF YOU FORGET JADE SUPPORT I WILL CRY
- [ ] Put a warning about cross pattern contamination as how regular machines behave, and that it will be fixed eventually
- [ ] Actual Recipe (LuV Assline)
- [ ] Any other Things Reviewers of this PR might fight horrendous and leave as review (Calling it now I will have to reoganize the location of some classes most likely.)

GOAL : 
Create a Multipart for GTCEU multiblocks that allows direct insertion of ME Patterns in its internal inventory. Allowing for easier automation when in combination with ME output Bus/Hatches. This Multipart will be usable from Post Assline progression, however if other devs feel it is still hilariously too strong, we can move it to post Mk1 Fusion and require Ruthenium.
This PR also servers to help aid #1731 from @screret migrate GE parts of old to present without any issues.

2024-08-16 09:53 UTC, Ghostipedia commented
I strongly have a love/hate relationship with spotless 🙃

2024-08-16 21:45 UTC, Ghostipedia commented
Today we learn a valuable lesson.
Lombok is evil. static final vars and lombok and super inheretance I hate I hate I hate I hate I hate I hate

2024-08-16 21:46 UTC, Ghostipedia commented
This post was sponsored by 3-4hours of painful DEBUGGING A VERY """OBVIOUS""" ISSUE

2024-08-17 05:24 UTC, Ghostipedia commented
A Visual Example of the new textures
https://github.com/user-attachments/assets/178a69ca-c6f1-411c-84d6-67b932b59882

2024-08-17 10:15 UTC, screret requested changes

2024-08-17 10:15 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/utils/GTNBTUtils.java
> +    public static CompoundTag writeItemStack(ItemStack itemStack, CompoundTag compoundTag) {
These already exist in GTUtil

2024-08-17 10:15 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/machine/fancyconfigurator/MEFancyInvConfigurator.java
> +public class MEFancyInvConfigurator implements IFancyConfigurator {
just name this `FancyInvConfigurator`, since it isn't specific to ME parts in any way.

2024-08-17 10:15 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/machine/fancyconfigurator/MEFancyTankConfigurator.java
> +public class MEFancyTankConfigurator implements IFancyConfigurator {
name this `FancyTankConfigurator`

2024-08-17 10:15 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEPatternBufferPartMachine.java
> +        // "gui.gregiceng.auto_return.desc.disabled"))));
just remove this?

2024-08-17 10:15 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEPatternBufferPartMachine.java
> +            // TODO: Actually give it the right AEItemKey rather than dirt and feeding it its own name lmoa
this TODO should probably be done?

2024-08-17 10:15 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEPatternBufferPartMachine.java
> +                                                                   List<FluidIngredient> left, boolean simulate) {
remove this newline

2024-08-17 10:15 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEPatternBufferProxy.java
> +    protected MEPatternBufferPartMachine.InternalSlot[] internalInventory = new MEPatternBufferPartMachine.InternalSlot[MAX_PATTERN_COUNT];
remove the initialization, it goes unused anyway and can break the saving logic.

2024-08-17 10:15 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/trait/MEPatternBufferRecipeHandler.java
> +        }
remove, it's useless.

2024-08-17 10:15 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/trait/MEPatternBufferRecipeHandler.java
> +            return 1D;
this should return `0.0D`

2024-08-17 10:15 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/trait/MEPatternBufferRecipeHandler.java
> +            return 1D;
this should return `0.0D`

2024-08-17 15:47 UTC, Ghostipedia commented
Wahoo! Checks Passed, this is good to go!

2024-08-17 15:50 UTC, screret approved these changes
wait for approval from someone else as well if possible.
also, testing.

2024-08-17 16:11 UTC, merged