Fluid Tag for molten fluids
GregTechCEu/GregTechCEu-1.19 pull request #1789
Opened 2024-08-20 00:51 UTC by YoungOnionMC

## What
also a recipe for fluid tag filter, oops

2024-08-20 05:01 UTC, screret requested changes

2024-08-20 05:01 UTC, screret commented on src/generated/resources/data/forge/tags/fluids/molten.json
DO NOT DATAGEN IT.

2024-08-20 05:01 UTC, screret commented on src/generated/resources/data/forge/tags/fluids/molten.json
do it in the injected tags instead.

2024-08-21 02:28 UTC, Ghostipedia approved these changes

2024-08-21 02:28 UTC, Ghostipedia approved these changes

2024-08-25 07:46 UTC, screret approved these changes

2024-08-25 07:50 UTC, merged