Fix OutputItems in kubeJS stripping NBT
GregTechCEu/GregTechCEu-1.19 pull request #1852
Opened 2024-08-31 03:14 UTC by YoungOnionMC

2024-08-31 03:44 UTC, YoungOnionMC commented
fixes #1829

2024-08-31 06:05 UTC, screret requested changes

2024-08-31 06:05 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/integration/kjs/recipe/components/GTRecipeComponents.java
> +    public static final RecipeComponent<OutputItem> OUTPUT_ITEM = new RecipeComponent<>() {
Just remove this if we're going back to OutputItem.

2024-09-01 09:51 UTC, screret approved these changes

2024-09-01 15:04 UTC, Ghostipedia approved these changes

2024-09-01 15:04 UTC, merged