Energy overlay rework
GregTechCEu/GregTechCEu-1.19 pull request #1861
Opened 2024-08-31 19:12 UTC by Xavier00014

## What
Reorganize energy overlay to be more consistently link to its behavior

## Outcome
Make it easier to tell how much power can be handled by a component

## Additional Information
![2024-08-25_15 20 45](https://github.com/user-attachments/assets/723d6bf8-c8ce-4432-a43a-fa4cb460f893)

Alos wanted to change FE converter texture to stand out more compared to the 4a eu texture but wasn't able to make something that look good

## Potential Compatibility Issues
Resource pack and add-ons may need to update if they use an energy overlay

2024-08-31 19:18 UTC, screret reviewed
run spotlessApply please.

2024-08-31 19:48 UTC, Ghostipedia requested changes
Un-tint the overlays. See your before image as to how the original transformers didn't have this issue of having a color multiplier applied to them, ideally fix this for the input/outputs too.
Otherwise it's going to be equally hard to figure out which is in/out

2024-08-31 21:05 UTC, Xavier00014 commented
I don't think I understand what is the issue, I can't see a difference in the color of the transformer(second row from the bottom). 
The only part on which i made color change are diode(Bottom row) and FE converter(left corner) but only for the EU side. 
Maybe my screenshot didn't make it clear what are the change that I made or you are taking about diode were I could agree it is little bit difficult to figure out i/o, but I don't have a solution that can keep the overlay consistent and easy to identify without making different shape for input and output.

2024-08-31 21:08 UTC, Ghostipedia commented
> I don't think I understand what is the issue, I can't see a difference in the color of the transformer(second row from the bottom). The only part on which i made color change are diode(Bottom row) and FE converter(left corner) but only for the EU side. Maybe my screenshot didn't make it clear what are the change that I made or you are taking about diode were I could agree it is little bit difficult to figure out i/o, but I don't have a solution that can keep the overlay consistent and easy to identify without making different shape for input and output.

![FNgJzMj6Wv](https://github.com/user-attachments/assets/b22f02e7-c9e5-48af-9eb1-726580a2d50b)

2024-08-31 21:13 UTC, Ghostipedia commented
To elaborate a bit more. Two things basically need to happen
- overlay layer one needs to be the 'grayscale' part of the texture, and that needs to be tinted appropriately per hull tier.
- overlay layer two needs to contain the 'ring' or part of the texture that shouldn't be affected by tinting, as that's how 1.12 does it. 
After further observation it just seems to be all over the place. but what I've listed here is what should happen.

2024-09-03 15:45 UTC, Ghostipedia approved these changes

2024-09-03 17:30 UTC, screret commented on src/main/resources/assets/gtceu/models/block/overlay/tinted/front_2.json
> +                "north": {"uv": [0, 0, 16, 16], "texture": "#overlay", "cullface": "north", "tintindex": -1 }
just remove the "tintindex": -1 entirely.

2024-09-05 13:56 UTC, screret approved these changes

2024-09-05 14:05 UTC, merged