Fix reslocs for several autogenerated recipes
GregTechCEu/GregTechCEu-1.19 pull request #1862
Opened 2024-08-31 20:43 UTC by Rundas01

## What
changed cursed and incorrect reslocs

2024-08-31 20:44 UTC, Rundas01 commented
Would like to label this, but I'm not allowed to

2024-08-31 20:49 UTC, screret requested changes

2024-08-31 20:49 UTC, screret commented on src/generated/resources/assets/gtceu/lang/en_ud.json
> +  "material.gtceu.arcubisite": "ǝʇısıqnɔɹⱯ",
remove this from your kjs materials.

2024-09-01 07:46 UTC, screret approved these changes

2024-09-01 08:26 UTC, merged