Assorted fixes
GregTechCEu/GregTechCEu-1.19 pull request #1886
Opened 2024-09-03 03:12 UTC by krossgg

## What
- Added new lang for rotor obstruction tooltip in turbine UIs, previously it used the muffler hatch obstruction message
- Fixed the step-assist behavior

## Implementation Details
Unfortunately this is only possible with an EventHandler via the Forge Event Bus, as I can't find another way to check if the boots has been taken off in order to reset the step-assist. 
To achieve this in a more robust manner, I added a new tag, gtceu:step_boots, which is used in the check. This allows for addon devs to add their own step-assist boots.

## Outcome
Fixes #1646

2024-09-03 09:35 UTC, screret requested changes

2024-09-03 09:35 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/item/armor/ArmorLogicSuite.java
> +    // Could potentially be put in ClientProxy
put it in ForgeCommonEventListener.

2024-09-04 01:41 UTC, krossgg commented
oops sorry I requested it from you directly screret

2024-09-04 05:17 UTC, screret requested changes

2024-09-04 05:17 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/item/armor/ArmorLogicSuite.java
> +        MinecraftForge.EVENT_BUS.register(this);
Remove, this is not a fast operation to do for no reason

2024-09-04 07:17 UTC, krossgg commented
Could you rerun the checks? I think gh decided I wasn't worth its time D:

2024-09-04 07:20 UTC, YoungOnionMC commented
got you fam

2024-09-04 07:26 UTC, screret approved these changes

2024-09-05 05:45 UTC, merged