Add missing flags for materials
GregTechCEu/GregTechCEu-1.19 pull request #2024
Opened 2024-09-24 23:33 UTC by JuiceyBeans

## What
Adds a bunch of missing flags to a ton of materials so that their tool recipes generate
Also adds a bunch of debug lines to catch missing flags for materials

## Outcome
A lot of tool parts are now craftable

2024-09-26 11:22 UTC, screret approved these changes

2024-09-29 12:19 UTC, JuiceyBeans commented
Before merging, do check whether the debug lines should be left in. Console will always complain about missing screw for wood, polybenzimidazole, polyethylene, PTFE, rubber in its current state

2024-09-29 14:11 UTC, screret requested changes

2024-09-29 14:11 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/ToolRecipeHandler.java
> +                    GTCEu.LOGGER.info("Did not find gear for for " + material.getName() +
for for

2024-09-29 14:11 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/ToolRecipeHandler.java
> +            GTCEu.LOGGER.info("Did not find rod for for " + material.getName() +
for for

2024-09-29 14:11 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/ToolRecipeHandler.java
> +                GTCEu.LOGGER.info("Did not find plate for for " + material.getName() +
for for

2024-09-29 14:11 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/ToolRecipeHandler.java
> +                            .info("Did not find bolt for for " + material.getName() + ", skipping wirecutter recipe");
for for

2024-09-29 14:11 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/ToolRecipeHandler.java
> +            GTCEu.LOGGER.info("Did not find plate for for " + material.getName() +
for for

2024-09-29 14:11 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/ToolRecipeHandler.java
> +                GTCEu.LOGGER.info("Did not find long rod for for " + material.getName() +
for for

2024-09-30 07:52 UTC, screret approved these changes

2024-10-01 07:41 UTC, merged