Rewrite OreDictExprFilter to fix tag filter functionality
GregTechCEu/GregTechCEu-1.19 pull request #2220
Opened 2024-10-19 20:32 UTC by bdemmy

## What
Rewrite OreDictExprFilter to fix tag filter functionality

## Implementation Details
Not really much besides rewriting parser / evaluator for tag filters.

## Additional Information
None

## Potential Compatibility Issues
None

2024-10-23 07:52 UTC, screret requested changes

2024-10-23 07:52 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/utils/OreDictExprFilter.java
> +        abstract static public class MatchExpr {
`public static abstract class` please.

2024-10-23 07:52 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/utils/OreDictExprFilter.java
> +        static class UnaryExpr extends MatchExpr {
why are all of these package-private instead of public or protected?

2024-10-23 07:52 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/utils/OreDictExprFilter.java
> +                .map(rl -> rl.getNamespace() + ":" + rl.getPath()).collect(Collectors.toSet());
```suggestion
                .map(ResourceLocation::toString).collect(Collectors.toSet());
```

2024-10-23 07:52 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/utils/OreDictExprFilter.java
> +    public static boolean matchesOreDict(OreDictExprParser.MatchExpr expr, ItemStack stack) {
rename this to `tagsMatch` or such

2024-10-23 07:52 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/utils/OreDictExprFilter.java
> +    public static boolean matchesOreDict(OreDictExprParser.MatchExpr expr, FluidStack stack) {
rename this to `tagsMatch` or such

2024-10-23 07:52 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/utils/OreDictExprFilter.java
> +                .map(rl -> rl.getNamespace() + ":" + rl.getPath()).collect(Collectors.toSet());
```suggestion
                .map(ResourceLocation::toString).collect(Collectors.toSet());
```

2024-10-23 07:52 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/utils/OreDictExprFilter.java
>  public class OreDictExprFilter {
this class should probably be named `TagExprFilter` or `TagExpressionFilter`.

2024-10-23 13:30 UTC, cnf13 commented on src/main/java/com/gregtechceu/gtceu/utils/OreDictExprFilter.java
>  public class OreDictExprFilter {
For a lot of these names I was just keeping the original names. Np changing them though. Thanks!

2024-10-26 10:41 UTC, screret approved these changes

2024-10-26 10:43 UTC, merged