realgar
GregTechCEu/GregTechCEu-1.19 pull request #2222
Opened 2024-10-19 21:56 UTC by Spicierspace153

adds more realgar in coppertin veins

2024-10-19 22:10 UTC, Spicierspace153 commented
fixes issue #2212

2024-10-19 22:49 UTC, YoungOnionMC approved these changes

2024-10-23 07:59 UTC, screret requested changes, later dismissed

2024-10-23 07:59 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/GTOres.java
> +                    .rareBlock(new VeinBlockDefinition(Realgar, 2))
this change does literally nothing as there's only 1 rare block. increase `rareBlockChance` instead

2024-11-12 04:03 UTC, YoungOnionMC approved these changes

2024-11-12 04:03 UTC, merged