Filter Cover Directionality
GregTechCEu/GregTechCEu-1.19 pull request #2343
Opened 2024-11-14 06:04 UTC by YoungOnionMC

## What
Adds in directionality rules for filter covers, and allows backflow(filtered or unfiltered)

2024-11-17 04:14 UTC, Ghostipedia approved these changes

2024-11-25 05:24 UTC, krossgg requested changes

2024-11-25 05:24 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/misc/IOFluidHandlerList.java
>          return super.drain(maxDrain, action);
```suggestion
        if (!io.support(IO.OUT)) return FluidStack.EMPTY;
        var fluidStack = super.drain(maxDrain, FluidAction.SIMULATE);
        if (fluidStack.isEmpty() || !outFilter.test(fluidStack)) return FluidStack.EMPTY;
        return action.simulate() ? fluidStack : super.drain(maxDrain, action);
```

2024-11-25 05:24 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/misc/IOFluidHandlerList.java
> +        return action == FluidAction.SIMULATE ? fluidStack : super.drain(resource, action);
```suggestion
        if (!io.support(IO.OUT) || !outFilter.test(resource)) return FluidStack.EMPTY;
        return super.drain(resource, action);
```

2024-11-25 05:27 UTC, krossgg approved these changes

2024-11-25 07:36 UTC, merged