Update Fluid slot behaviour
GregTechCEu/GregTechCEu-1.19 pull request #2422
Opened 2024-11-22 22:03 UTC by Natanaelel

- fluid containers stays in cursor
- return overflow with vanilla `placeItemBackInInventory`
- fix sound not playing when emptying slot completely

## What
_This section describes what this PR is about. It should be a clear and concise description concerning what this PR is for, why this PR is needed, and why it should be accepted._
_Linking an issue can be used alternatively to writing a description._

## Implementation Details
_Any implementations in this PR that should be carefully looked over, or that could/should have alternate solutions proposed._

## Outcome
_A short description of what this PR added/fixed/changed/removed._
_For correct linking of issues please use any of the Closes/Fixes/Resolves keywords. Example: When a PR is fixing a bug use "Fixes: #number-of-bug"_

## Additional Information
_This section is for screenshots to demonstrate any GUI or rendering changes, or any other additional information that reviewers should be aware of._

## Potential Compatibility Issues
_This section is for defining possible compatibility issues. It must be used when there are API changes, item/block/material/machine changes, or recipe changes._

**Please fill in as much useful information as possible. Also, please remove all unused sections, including this and the other explanations.**

2024-11-23 02:14 UTC, krossgg requested changes

2024-11-23 02:14 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/gui/widget/TankWidget.java
> +        FluidStack initialFluidCopy = initialFluid.copy();
Honestly, we don't even use the `initialFluid` var anymore, so you could just store the fluid type of the initial fluid to get the sound from, eliminating the need for a copy.

2024-11-23 02:14 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/gui/widget/TankWidget.java
> +                    filledResult = remainingStack.copy();
Last branch of if/else chain has brackets, so all branches should have brackets for clarity

2024-11-23 02:14 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/gui/widget/TankWidget.java
> +                    drainedResult = remainingStack.copy();
Last branch of if/else chain has brackets, so all branches should have brackets for clarity

2024-11-23 02:16 UTC, krossgg commented
Next time, please fill out the template better to provide more information and remember to delete the unused sections (like it says to).

2024-11-23 08:08 UTC, Natanaelel commented on src/main/java/com/gregtechceu/gtceu/api/gui/widget/TankWidget.java
> +        FluidStack initialFluidCopy = initialFluid.copy();
It gets modified during the draining, which was the reason for the sound bug.

2024-11-25 07:34 UTC, krossgg approved these changes

2024-11-25 07:46 UTC, YoungOnionMC approved these changes

2024-11-25 07:54 UTC, merged