Fix data stick not copying distinct bus from me input bus
GregTechCEu/GregTechCEu-1.19 pull request #2448
Opened 2024-11-28 14:10 UTC by omergunr100

## What
Adds the distinct bus field to the copied and pasted nbt.

## Suggestion
I suggest unifying the configuration copy pasting to a single interface that lets you:
1. Copy machine configuration as nbt.
2. Paste machine configuration as nbt.
3. Get what tools/items are allowed to copy/paste this machine configuration (if we want to keep this behaviour on the data stick)

(personal opinion warning)
I think the data stick interaction is a bit weird, we have a way of doing exactly that with item behaviours. (also see #2405 )
also copying on left click feels a bit clunky to me, I feel like copying on `shift + <copy key>` feels better but that's just me.

## Also
Fixes #2344

2024-11-29 10:19 UTC, screret requested changes, later dismissed

2024-11-29 10:19 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEInputBusPartMachine.java
> +        tag.putBoolean("DistinctBusses", isDistinct());
it's "Buses" with 1 `s`

2024-11-29 10:19 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEInputBusPartMachine.java
> +            setDistinct(tag.getBoolean("DistinctBusses"));
it's "Buses" with 1 `s`

2024-12-01 08:11 UTC, YoungOnionMC approved these changes

2024-12-01 10:22 UTC, screret approved these changes

2024-12-01 10:37 UTC, merged