Refactor Cleanroom and CharcoalPileIgnitor Structure Check
GregTechCEu/GregTechCEu-1.19 pull request #2466
Opened 2024-12-01 05:59 UTC by YoungOnionMC

## What
Refactors the entire structure builder for both cleanroom and charcoal pile ignitor multis
Adds in a map for valid blocks in the cleanroom floor
Fixes #2419 

## Implementation Details
The layer StringBuilders are done from bottom up instead of left to right like it used to

## Outcome
More flexibility in building a cleanroom

2024-12-01 10:24 UTC, screret requested changes

2024-12-01 10:24 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/config/ConfigHolder.java
> +        @Configurable
make this a tag instead of a config

2024-12-01 20:14 UTC, screret requested changes

2024-12-01 20:14 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/electric/CleanroomMachine.java
> +                state.is(CustomTags.CLEANROOM_FLOORS);
remove the 1st 2 cases, useless

2024-12-01 20:14 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/tags/BlockTagLoader.java
> +        create(provider, CustomTags.CLEANROOM_FLOORS, GTBlocks.PLASTCRETE.get(), GTBlocks.CLEANROOM_GLASS.get());
cleanroom glass shouldn't be a valid floor block, only a wall block

2024-12-01 20:25 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/electric/CleanroomMachine.java
> +
actually this could just use `Predicates.blockTag`

2024-12-01 20:37 UTC, screret approved these changes

2024-12-02 06:37 UTC, screret approved these changes

2024-12-02 06:38 UTC, merged

2024-12-07 06:37 UTC, tomprince commented on src/generated/resources/data/gtceu/tags/blocks/cleanroom_floors.json
> +    "gtceu:cleanroom_glass"
I was testing this on 1.20.1-1.5.5 SNAPSHOT 20241206 and I'm not sure that these blocks should be here.

After adding a couple of more block to the tag, I tried placing two of them in the foor, one in the center, and one beside it. With only the center block replaced, the structure forms, but if I replace one of the surronding blocks it doesn't. However, if I remove these blocks from the tag, I can replace the surronding blocks and still have the structure form.

I suspect what is going on is that the blocks above are eating the global max, before falling back to the other alternatives.