Remove LdLib Compass Support
GregTechCEu/GregTechCEu-1.19 pull request #2467
Opened 2024-12-01 06:21 UTC by Ghostipedia

## What
Removes All Compass Content and Integration in GTCEU as a whole, as part of moving away from LDLIB reliance.

Compass is used nearly as frequently as Fabric was for us, but contributed to a bunch of code that had to still be maintained, slimming this down will mean less reliance on other project libraries. Myself and Several people are in favor of this (Namely Tech, Spicy, Onion, and myself)

## Implementation Details
Full Erases compass and all related content to it

## Outcome
Removes Compass

## Potential Compatibility Issues
If you are the 0.1% of people using compass, you will no longer be able to use it next major update, please look into using Patchouli or Modonomicon if you need a booklet guide.

## Additional Information
i was at house, eating chicken... when phone ring...
"Compass is kil"
"Yes..."
![366323089-506e888e-af82-43a2-a262-bce5e9495400](https://github.com/user-attachments/assets/a7846653-7aab-4bf4-820e-e03a28738bab)

2024-12-01 08:22 UTC, screret requested changes, later dismissed
:waaaaaaahhhhhhh:

2024-12-01 08:22 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/machines/GCYMMachines.java
> +
remove these newlines you left

2024-12-03 06:22 UTC, YoungOnionMC approved these changes

2024-12-03 06:23 UTC, merged

2024-12-03 06:23 UTC, krossgg commented
o7

2024-12-03 06:24 UTC, Spicierspace153 commented
O7

2024-12-03 06:25 UTC, JuiceyBeans commented
where were you when compass was kil. o7

2024-12-03 06:26 UTC, Deepacat commented
it wasn't that bad :(

2024-12-03 06:51 UTC, Ghostipedia commented
> it wasn't that bad :(

https://www.youtube.com/watch?v=Xsrjy7140Lw

2024-12-03 06:53 UTC, omergunr100 commented
I was walking the dog

Message pops on my phone

"Compass is kil"

"No"

2024-12-03 06:55 UTC, Spicierspace153 commented
i think there may be a typo there
it should be

"Compass is kil"

"Yes"