ender fluid cover imp
GregTechCEu/GregTechCEu-1.19 pull request #2505
Opened 2024-12-06 15:02 UTC by Arborsm

## What
This PR adds ender cover system.
﻿
## Implementation Details
The implementation includes new classes for virtual cover.
﻿
## Outcome
Players can now create customized virtual tanks for fluid management, enhancing the gameplay experience.
﻿
## Additional Information
show channel list is not finished, I can't make it work in server...

2024-12-06 15:22 UTC, screret requested changes

2024-12-06 15:22 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/cover/ender/CoverAbstractEnderLink.java
name this class `AbstractEnderLinkCover`

2024-12-06 15:22 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/misc/virtualregistry/VirtualEnderRegistry.java
> +                GTCEu.LOGGER.debug("VirtualEnderRegistry has been successfully loaded");
remove this debugging line

2024-12-06 15:22 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/cover/ender/CoverAbstractEnderLink.java
> +    protected UUID playerUUID = null;
this should use the team mod integration we have.

2024-12-06 15:22 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/cover/ender/EnderFluidLinkCover.java
> +    }
useless override

2024-12-06 15:22 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/misc/virtualregistry/EntryTypes.java
> +    }
make this take in a `ResourceLocation` as the parameter

2024-12-06 15:22 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/misc/virtualregistry/VirtualEntry.java
> +    }
`@Getter` and `@Setter`

2024-12-06 15:22 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/cover/ender/EnderFluidLinkCover.java
> +    // }
we'll figure out a solution here

2024-12-12 20:50 UTC, screret approved these changes

2024-12-12 20:52 UTC, screret commented
conflicts

2024-12-22 05:22 UTC, teh-banana commented
Doing some testing of this, and I have some questions / comments. I have bolded the more important / buggy parts of my comment.

Reference Screenshot:
![image](https://github.com/user-attachments/assets/eea7022f-39e6-4068-96b5-dacaf6013b94)

I have opened the UI to edit from inside a machine, and **the `X` to close the cover is overlaid with the list of "ender tanks".**

~~Also I have no clue what the large text box does. I tried putting in text and clicking the check mark but it did not save what I thought would be a description?~~ Oh apparently it is a description, just didn't save the first time, and I was unable to find anything in the logs about it. **There seems to be some buggy behaviour around this saving information, it seems to get cleared when you open the cover / load the tank colour on another block and the internal tank is empty**.

I am curious as to why the hex for the colour has an alpha channel in it too, my only thought is that it gives more options for similar colours, but things using minecraft colours typically don't have an alpha (see other mod's ender tanks which just implement the 16 minecraft colours).

Some **more tooltips on the different elements of the UI** would help with figuring out what stuff does. 

![image](https://github.com/user-attachments/assets/9fa2d00f-e72d-4462-8db2-0c1995367804)

I feel like **the tooltip or the image on the lock is backwards**. To me the icon indicates that the cover is currently in an "unlocked" state aka public, but then the tooltip seems to indicate that clicking on the button will switch the tank to public. Maybe it should say something along the lines of: (also include a description for public when it is public, and the existing private description when it is private)

```
Current mode: Public/Private
Click to switch mode
```

I have ***NOT*** tested this on a server yet, waiting for another PR to be merged and pulled into this PR.

2024-12-22 06:02 UTC, Arborsm commented
alpha and tooltip just use ceu things

2024-12-22 06:03 UTC, Arborsm commented
wait the tooltip is reverse ..

2024-12-22 06:06 UTC, Arborsm commented
> **There seems to be some buggy behaviour around this saving information, it seems to get cleared when you open the cover / load the tank colour on another block and the internal tank is empty**.

because it's design to auto-delete, and if other ender cover has this channel it will be auto recreated

2024-12-23 06:24 UTC, screret commented
Remove Do Not Merge label once this has been thoroughly tested for edge cases.

2025-04-01 09:14 UTC, screret commented
was this ever actually tested?

2025-04-01 09:20 UTC, screret requested changes

2025-04-01 09:20 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/misc/virtualregistry/VirtualEntry.java
> +    public static int parseColor(String colorString) {
so you take in ARGB colors and then discard the alpha?
but also require the color value to actually be RGBA or the color will be wrong?

2025-04-01 09:20 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/cover/ender/EnderFluidLinkCover.java
> +    }
just use `@Getter` for this

2025-04-01 09:20 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/lang/LangHandler.java
> +        provider.add("cover.ender_fluid_link.tooltip.channel_name", "Set channel name with input text");
```suggestion
        provider.add("cover.ender_fluid_link.tooltip.channel_description", "Channel description");
        provider.add("cover.ender_fluid_link.tooltip.channel_name", "Channel name");
```

2025-04-01 09:22 UTC, Arborsm commented on src/main/java/com/gregtechceu/gtceu/api/misc/virtualregistry/VirtualEntry.java
> +    public static int parseColor(String colorString) {
just discard the alpha

2025-04-01 10:18 UTC, closed without merging