Distinct Fluid Behaviour and Recipe Runner Refactor
GregTechCEu/GregTechCEu-1.19 pull request #2544
Opened 2024-12-14 10:02 UTC by YoungOnionMC

## What
Refactored how the recipe runner class handled searching and consuming contents of a recipe based on the current handler trying to process that recipe, in short distinct fluid hatches are now possible.

## Implementation Details
Refactors out the recipe handling related functions out of `GTRecipe` and into their own class `RecipeHandler`, switched the capability proxy table into a double nested map for better clarity. Unified `RecipeRunner` to handle  the entire map of recipe contents at once instead of on a per capability basis. Got rid of references to the unused slot naming system in recipe searching and handling. Adds Recipe ActionResults to various method for logging how a recipe search or handle method failed

## Outcome
TBD

2025-03-04 06:07 UTC, krossgg requested changes, later dismissed
Comments for myself

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/machine/multiblock/WorkableMultiblockMachine.java
> +    protected Map<IO, Map<RecipeCapability<?>, List<IRecipeHandler<?>>>> capabilitiesFlat;
Make final (same with other classes)

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/ActionResult.java
> +public record ActionResult(boolean isSuccess, Supplier<@Nullable Component> reasonSupplier) {
Don't think this needs to be a supplier

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeHelper.java
> +        // TODO: make this actually log error on failed non-simulate
Do this

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeHelper.java
> +        GTRecipe current = recipe.copy();
I think this copy is unnecessary? Check if the `GTRecipeBuilder` call does a shallow copy.

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeHelper.java
> +     * @param trimLimits The limit(s) on the number of outputs, -1 for disabled.
I think this -1 is just a lie - check this with `IVoidable`

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeHelper.java
> +    public static Map<RecipeCapability<?>, List<Content>> doTrim(Map<RecipeCapability<?>, List<Content>> current,
Clean this entire method up

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeRunner.java
> +    record RecipeHandlingResult(@Nullable RecipeCapability<?> capability, @UnknownNullability List content,
See if list is actually necessary anywhere

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeRunner.java
>  class RecipeRunner {
See if we can just use one instance for the entire recipe run, used for matching AND handling

Also go over all logic in this class again

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/lookup/GTRecipeLookup.java
>      protected List<List<AbstractMapIngredient>> prepareRecipeFind(@NotNull IRecipeCapabilityHolder holder) {
Go over this again

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/electric/AssemblyLineMachine.java
>      public boolean beforeWorking(@Nullable GTRecipe recipe) {
Check this in game

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/electric/DistillationTowerMachine.java
> +                    var handler = part.getRecipeHandlers().get(0).getCapability(FluidRecipeCapability.CAP)
Test this in game

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/electric/research/NetworkSwitchMachine.java
> +            List<IOpticalComputationHatch> list;
Test in game

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/part/ItemBusPartMachine.java
> +        getRecipeHandlers().get(0).setDistinct(getInventory().isDistinct());
Make distinctness persist on the machine itself rather than the inventory

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/primitive/PrimitivePumpMachine.java
> +            var handlerLists = part.getRecipeHandlers();
Test in game

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/steam/SteamParallelMultiblockMachine.java
> +        var handlers = getCapabilitiesFlat(IO.IN, FluidRecipeCapability.CAP);
Maybe make this look specifically for the steam hatch so that addons can use other hatches for fluid recipes

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/machine/trait/customlogic/BreweryLogic.java
> +        // TODO: Make this use generic IRecipeHandlers and not Item/FluidHandlers - i.e. pattern buffer
Do this

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEPatternBufferPartMachine.java
> +    protected final InternalSlotRecipeHandler ISRHL;
Rename

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEPatternBufferPartMachine.java
> +            ListTag items = tag.getList("inventory", Tag.TAG_COMPOUND);
Consider adding backwards compat - or just tell people to empty them before updating

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEPatternBufferPartMachine.java
> +        private final Object2LongMap<ItemStack> itemInventory = new Object2LongOpenCustomHashMap<>(
Consider using AE keys instead of two maps

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/trait/InternalSlotRecipeHandler.java
> +public class InternalSlotRecipeHandler {
Go over this again

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/trait/ProxySlotRecipeHandler.java
> +public class ProxySlotRecipeHandler {
Go over this again

2025-03-04 06:07 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeHandlerList.java
> +    public List<ISubscription> addChangeListeners(Runnable listener) {
Think about having the RHL store and return one subscription rather than making each handler provide its own

2025-03-06 05:33 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEPatternBufferPartMachine.java
> +        private final Object2LongMap<ItemStack> itemInventory = new Object2LongOpenCustomHashMap<>(
Future endeavor - not sure the benefits it would bring

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/capability/recipe/IRecipeHandler.java
>          List<K> contents = new ObjectArrayList<>(left.size());
check if the content copy is really necessary

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/item/tool/ToolHelper.java
> +                        GTRecipeTypes.FORGE_HAMMER_RECIPES, GTMachineUtils.defaultTankSizeFunction,
does this really need a fake MBE for simulated recipe outputs?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/NotifiableFluidTank.java
> +         for (CustomFluidTank storage : this.storages) {
spotless?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/NotifiableFluidTank.java
> +//        boolean changed = false;
are these commented lines still needed?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeHandlerList.java
> +            for (var rht : allHandlerTraits) {
would there ever be a case in which some handlers would be not distinct and therefore not set if you reset distinctness in the list? aka move the iter out of the distinct flag setting?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeHandlerList.java
> +        return (extIO == IO.BOTH || handlerIO == IO.BOTH || extIO == handlerIO);
is (BOTH && NONE) valid?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeHandlerList.java
> +            if (handlerList == null) continue;
can the handler map have null entries?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeLogic.java
> +                    // or
fix formatting

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeLogic.java
> +            handleTickRecipeIO(recipe, IO.IN);
check if handleTickRecipeIO doesnt succeed and early exit, returning the result, (same as handleRecipeIO)

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/recipe/GTRecipeSerializer.java
> +                                      conditions, data, duration, recipeCategory) ->
check to make sure loading an old world with recipes that have fuel fields dont die with this pr applied

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/recipe/GTRecipeType.java
> +        if (!holder.hasCapabilityProxies()) return null;
should we return an empty iter instead?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeHelper.java
> +        if (!holder.hasCapabilityProxies() || io == IO.BOTH) return ActionResult.FAIL_NO_CAPABILITIES;
whats the reasoning behind failing io.BOTH?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeHelper.java
> +                GTCEu.LOGGER.warn("IO Error while handling recipe {} outputs for {}", recipe, holder);
log the io side?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeHelper.java
> +            if (!passed) return ActionResult.fail(Component.translatable("gtceu.recipe_logic.condition_fails"));
append all recipe conditions in current list that failed to the action?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeHelper.java
> +     * Trims the recipe outputs and tick outputs based on the performing Machine's trim limit.
note that it makes a recipe copy

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeRunner.java
> +                searchContentList.add(cont.content);
does the searchContentList still need populated if we arent simulating? (we should have already passed simulation at that point)

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeRunner.java
> +            handlers.sort(RecipeHandlerList.COMPARATOR.reversed());
handlers should be already sorted as per RHL#addHandlers, no?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/api/recipe/lookup/GTRecipeLookup.java
> +                    return null;
whats this max int check for? idt any recipe handler entry would be max int in size, otherwise it would overflow

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/electric/research/ResearchStationMachine.java
> +                holder.setDataItem(outputItem);
does this overwrite existing output items in the object holder if you run subsequent recipes, without removing first?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/primitive/PrimitivePumpMachine.java
> +            var handlerLists = part.getRecipeHandlers();
was this tested?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/steam/LargeBoilerMachine.java
> +                    outputTanks.addAll(getCapabilitiesFlat(IO.BOTH, FluidRecipeCapability.CAP));
is there a reason that IO.BOTH is populated for the steam holder?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/steam/SteamParallelMultiblockMachine.java
> +            assert steamEnergy != null : "Formed without Steam Hatch";
this container will never be null AND formed since if its null it invalidates the structure

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEPatternBufferPartMachine.java
> +        proxyMachines.remove(proxy);
this should be add, not remove

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/integration/jade/provider/MEPatternBufferProvider.java
> +                Component text = Component.literal(FormattingUtil.formatBuckets(amount))
no small fluid stack render?

2025-03-18 05:52 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/utils/DummyMachineBlockEntity.java
> +    // TODO: Fix the proxy parameter
was this ever fixed?

2025-03-18 06:45 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeHandlerList.java
> +            for (var rht : allHandlerTraits) {
No - `setDistinct` for `NotifiableRecipeHandlerTrait` is only ever called in this method now.

2025-03-18 06:50 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/item/tool/ToolHelper.java
> +                        GTRecipeTypes.FORGE_HAMMER_RECIPES, GTMachineUtils.defaultTankSizeFunction,
Yes, RecipeLookup requires an IRecipeCapabilityHolder and the dummy machine is the easiest way to do it.
This could be changed to do the lookup manually, converting the stack into an AbstractMapIngredient and searching for the recipe, but that is outside the scope of this PR.

2025-03-18 06:53 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeHandlerList.java
> +            if (handlerList == null) continue;
`Map#get` returns `null` if the key is not present.

2025-03-18 06:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeRunner.java
> +            handlers.sort(RecipeHandlerList.COMPARATOR.reversed());
`RHL#sort` sorts the *internal* lists in an RHL. This line sorts the IO.OUT RHLs.

2025-03-18 07:00 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/steam/LargeBoilerMachine.java
> +                    outputTanks.addAll(getCapabilitiesFlat(IO.BOTH, FluidRecipeCapability.CAP));
It's not populating it - its checking for any handlers that are `IO.BOTH` to use for output.

2025-03-18 07:04 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/steam/SteamParallelMultiblockMachine.java
> +            assert steamEnergy != null : "Formed without Steam Hatch";
...yes, that is why it is an assertion - the steam energy handler should *never* be null if the structure is formed.

2025-03-18 07:05 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/electric/research/ResearchStationMachine.java
> +                holder.setDataItem(outputItem);
Play GTM and see !

2025-03-18 07:18 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/utils/DummyMachineBlockEntity.java
> +    // TODO: Fix the proxy parameter
Yes

2025-03-18 07:20 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeHelper.java
> +        if (!holder.hasCapabilityProxies() || io == IO.BOTH) return ActionResult.FAIL_NO_CAPABILITIES;
Legacy. Unsure. I assume its because a recipe isn't supposed to be directly handled IO.BOTH, only input and output, so this is fail-fast

2025-03-18 08:56 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeRunner.java
> +                searchContentList.add(cont.content);
You might be right. Currently, the only place its actually being used is to check if the distinct bus we're using *can handle* all the contents including chanced ones. Will have to step through and see what happens if removed.

2025-03-18 08:58 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/GTRecipeType.java
> +        if (!holder.hasCapabilityProxies()) return null;
Sure.

2025-03-18 09:00 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/lookup/GTRecipeLookup.java
> +                    return null;
No clue. Legacy.

2025-03-18 09:01 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeRunner.java
>  class RecipeRunner {
Leaving this for separate PR focusing on RecipeLogic state machine

2025-03-22 00:28 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/capability/recipe/IRecipeHandler.java
>          List<K> contents = new ObjectArrayList<>(left.size());
Gonna say it is for now.

2025-03-25 20:56 UTC, omergunr100 requested changes, later dismissed

2025-03-25 20:56 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/trait/ProxySlotRecipeHandler.java
> +            var rhl = new ProxyRHL(machine);
Inline for clarity

2025-03-25 20:56 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeHandlerList.java
> +    public static RecipeHandlerList of(IO io, IRecipeHandler<?> handler) {
Make this method accept handler args instead of single instance and refactor uses of `new` + `addHandlers` to use it

2025-03-25 20:56 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeHelper.java
> +        return result.result();
Unwrap the condition:
```java
if (result.isSuccess() || result.capability() == null) return result.result();

if (!simulated) {
    GTCEu.LOGGER.warn("IO {} Error while handling recipe {} outputs for {}",
            Component.translatable(io.tooltip).getString(), recipe, holder);
}
String key = "gtceu.recipe_logic.insufficient_" + (io == IO.IN ? "in" : "out");
return ActionResult.fail(Component.translatable(key)
        .append(": ").append(result.capability().getName()));
```

2025-03-25 20:56 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/recipe/RecipeHelper.java
> +                return ActionResult.fail(Component.translatable("gtceu.recipe_logic.invalid_stack"));
Missing lang key

2025-03-25 20:56 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/recipe/ActionResult.java
> +            Component.translatable("gtceu.recipe_logic.no_contents"));
Missing lang key

2025-03-25 20:56 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/recipe/ActionResult.java
> +            Component.translatable("gtceu.recipe_logic.no_capabilities"));
Missing lang key

2025-03-25 20:56 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/machine/multiblock/WorkableMultiblockMachine.java
> +            for (long pos : activeBlocks) {
Might as well use an iterator to avoid boxing and unboxing

2025-03-25 20:56 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/machine/multiblock/part/MultiblockPartMachine.java
> +                handlerList.addHandlers(handlerTraits.toArray(new IRecipeHandler[0]));
Create an empty array instance to reuse or change it to `IRecipeHandler[]::new`, no reason to allocate 2 arrays

2025-03-25 21:15 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/machine/multiblock/WorkableMultiblockMachine.java
> +            for (long pos : activeBlocks) {
`activeBlocks` is a LongSet - no autoboxing here.

2025-03-28 08:07 UTC, Ghostipedia approved these changes

2025-03-28 08:07 UTC, merged