Item Material Information Refactor
GregTechCEu/GregTechCEu-1.19 pull request #2591
Opened 2024-12-19 10:01 UTC by YoungOnionMC

## What
Overhauls and breaks apart the various methods of `ChemicalHelper` into material related functions and the new `ItemMaterialInfo` methods, also renames `UnificationEntry` to the more suitable `MaterialEntry`.
There is also 2 new methods in `RecipeBuilder` for generating MaterialInfo for various gt recipes.

## Implementation Details
- [ ] Find a way for fluids to be included in RecipeBuilder decomp
- [ ] kube js support for completely overwriting java sided ITEM_MATERIAL_INFO
- [ ] remove MaterialInfoLoader in favor if adding recipe builder decomp to all assembler related recipes

2024-12-30 09:30 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/client/renderer/BlockHighlightRenderer.java
> +            }
ermh?

2024-12-30 09:30 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/forge/ForgeCommonEventListener.java
> +        // moved here so that we can get tag info for decomp recipes
my comment is just false lmo

2025-01-04 09:40 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/forge/ForgeCommonEventListener.java
> +        // moved here so that we can get tag info for decomp recipes
move this back to where it was originally.

2025-01-29 04:40 UTC, stanieldev approved these changes
I see no true issues for final commit, but I would definitely like some if statement blocks to be unwrapped and inverted for clarity for statement guarding.

I'll eventually get around to writing more JavaDocs when I don't think I'm gonna fail getting my degree because of capstone 😭

2025-01-29 04:40 UTC, stanieldev commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +    public static MaterialStack getMaterialStack(MaterialEntry entry) {
Consider inverting the conditions and unwrapping (using early returns)

2025-01-29 04:40 UTC, stanieldev commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/trait/MEPatternBufferProxyRecipeHandler.java
> +        double amount = 0.;
I love java syntax :D 🗡️

2025-01-29 04:43 UTC, stanieldev commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/trait/MEPatternBufferProxyRecipeHandler.java
> +        double amount = 0.;
There's nothing wrong here. I just find lone periods after numbers to be one of the worst syntax decisions done by a programming language :3

2025-01-29 04:44 UTC, stanieldev commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +    public static MaterialStack getMaterialStack(MaterialEntry entry) {
Oof, wrong line. There are a lot of these but I didn't bother outlining every single one.

I could make a PR that just inverts and returns early as its premise.

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/integration/kjs/GregTechKubeJSPlugin.java
> +                    return new MaterialEntry(TagPrefix.get(values[0]));
Why is this even an option?

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/ItemMaterialInfo.java
> +    private List<MaterialStack> sortedMaterials = new ArrayList<>();
Make members `final`

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/MaterialEntry.java
> +    public static final MaterialEntry NullEntry = new MaterialEntry(null, null);
If there's a reason to keep this then use `TagPrefix.nullPrefix` instead of null.

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/MaterialEntry.java
> +public record MaterialEntry(TagPrefix tagPrefix, @Nullable Material material) {
Mark `tagPrefix` as not null since we have `TagPrefix.nullPrefix` for that.

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
>      public static List<Map.Entry<ItemStack, ItemMaterialInfo>> getAllItemInfos() {
Just return a map lol, it's used in only 1 place and would benefit from using the map (key, value) iterator

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
>      }
Currently entry will never be null, just mark the parameter not null instead.

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +        var unifyingEntry = ItemMaterialData.ITEM_MATERIAL_ENTRY_COLLECTED.get(itemKey);
Rename to `materialEntry` for consistency

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +            for (TagKey<Block> tag : Arrays.stream(getTags(materialEntry.tagPrefix(), materialEntry.material()))
If `MaterialEntry.material` should be nullable there should be a null check before this line.

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/worldgen/generator/VeinGenerator.java
> +                                Function.identity()) !=
wtf did spotless do to my boy?!
pls manually delete the extra line

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/common/data/GTRecipes.java
> +        if (!GTCEu.isKubeJSLoaded()) {
!GTCEu.Mods.isKubeJSLoaded()

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +    public static MaterialEntry getMaterialEntry(ItemLike itemLike) {
`OreVeinIcon` line 68 should use this instead of whatever it's doing rn

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/client/TooltipsHandler.java
> +        var unificationEntry = ChemicalHelper.getMaterialEntry(stack.getItem());
Rename to `materialEntry`

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/client/renderer/BlockHighlightRenderer.java
>                  .endVertex();
Please reformat properly, either one line per method call or squash them both. (I prefer the former)

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/data/recipe/MaterialInfoLoader.java
> +         */
⁉️

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +        var matStack = ItemMaterialData.getMaterialInfo(input);
This will always be null

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +        }
Why is this even necessary? 
The item is passed to another method that'll add it properly.

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +            tempItemMaterialStacks
If the material isn't null it'll be added twice

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +        if (chance == maxChance) {
Remove this check, it'll just add a duplicate entry

2025-02-21 00:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/data/recipe/configurable/RecipeAddition.java
> +                    'C', new MaterialEntry(TagPrefix.spring, GTMaterials.Iron));
This should've been a part of a recipe pr, not the material refactor.
@Ghostipedia would appreciate you checking it out.

2025-02-21 03:46 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/data/recipe/configurable/RecipeAddition.java
> +                    'C', new MaterialEntry(TagPrefix.spring, GTMaterials.Iron));
it was? those lines were added as part of #2077, i was just fixing the UnificationEntry->MaterialEntry naming

2025-02-21 19:05 UTC, screret approved these changes
its fine ig
wait for someone to do a thorough review though, I just read changes from last review

2025-02-23 20:47 UTC, omergunr100 requested changes, later dismissed
logic looks good but run `spotlessApply`

2025-02-23 20:48 UTC, omergunr100 commented
wrong pr

2025-02-24 01:15 UTC, omergunr100 requested changes
you missed a unification entry so the build is failing.

we also need to try and replace those concurrent collections in `ItemMaterialData` with fast ones and see if it breaks.

2025-03-04 01:27 UTC, krossgg requested changes
I want to look over all the streams too - there's a lot of long/nested ones that could probably be simplified. Will do it whenever I get on my pc.

Can you do more extensive testing with and without kube and make sure we didn't need those concurrent maps?

2025-03-04 01:27 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +        ItemMaterialInfo info = ItemMaterialData.ITEM_MATERIAL_INFO.get(itemLike);
Just import static from `ItemMaterialData` so you don't have to qualify all these maps every time.

2025-03-04 01:27 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +            for (TagKey<Block> tag : Arrays.stream(getTags(materialEntry.tagPrefix(), materialEntry.material()))
Might just be better to do another outer for loop rather than doing this stream with a single mapping

2025-03-04 01:27 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +    public static final Map<ItemStack, List<ItemStack>> UNRESOLVED_ITEM_MATERIAL_INFO = new Object2ReferenceOpenCustomHashMap<>(
why is this an object2ref map? I don't believe it's necessary

2025-03-04 01:27 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/MaterialEntry.java
> +    }
These are unnecessary by virtue of the class being a `record`

2025-03-04 01:27 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/MaterialEntry.java
> +    public static final MaterialEntry NullEntry = new MaterialEntry(TagPrefix.nullPrefix, GTMaterials.NULL);
Move this to the top of the class, also `NULL_ENTRY`

2025-03-04 01:27 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/MaterialEntry.java
> +public record MaterialEntry(@NotNull TagPrefix tagPrefix, @NotNull Material material) {
The material is marked `@NotNull` yet I see many instances of you null checking `entry.material()` - did you mean to do an equality check with `GTMaterials.NULL`?

2025-03-04 01:27 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +        // resolveFluidMaterialInfos(context);
?

2025-03-04 01:27 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +                            ItemMaterialData.FLUID_MATERIAL.put(pair.getFirst(), material);
Unnecessary qualification

2025-03-04 01:27 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/trait/MEPatternBufferProxyRecipeHandler.java
> +        double amount = 0.;
Remove the `.`, the type is enough.

2025-03-04 01:27 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/SizedIngredient.java
> +        List<ItemStack> list = Lists.newArrayList();
why the guava? it literally just returns `new ArrayList<>()`

2025-03-04 01:27 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/data/GTRecipes.java
> +    public static ICondition.IContext RECIPE_CONTEXT = null;
I'll have to open this PR in IntelliJ myself later, but can you point me to where this value is actually *set*?

2025-03-06 17:11 UTC, omergunr100 requested changes
I can't mark the line in this review since the file hasn't been changed, but look at `MaterialStack.isEmpty()` it checks if the material is air, air is a valid material it should be `GTMaterials.NULL` imo.

Also consider adding an empty material stack to `MaterialStack`:
```Java
public static final MaterialStack EMPTY = new MaterialStack(GTMaterials.NULL, 0);
```
that way we could make all the material stack helper methods `@NotNull` and replace all the `materialStack.material() == GTMaterial.Null` checks with `materialStack.isEmpty()` which makes more sense and is easier to work with imo.

2025-03-07 08:03 UTC, omergunr100 requested changes
Just adding `isEmpty()` isn't good for anything if we don't use it

2025-03-07 08:03 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/common/machine/steam/SteamSolidBoilerMachine.java
> +        if (materialStack == MaterialStack.EMPTY)
look here

2025-03-07 08:03 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +                if (ms != MaterialStack.EMPTY) return ms;
look here too

2025-03-07 08:03 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/data/recipe/VanillaRecipeHelper.java
> +            if (materialStack != MaterialStack.EMPTY && !(materialStack.material() instanceof MarkerMaterial)) {
look

2025-03-07 08:03 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/data/recipe/misc/RecyclingRecipes.java
> +            if (ms == MaterialStack.EMPTY || ms.material() == GTMaterials.NULL) {
look here too

2025-03-07 08:03 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/data/recipe/misc/RecyclingRecipes.java
> +        if (prefix == TagPrefix.DUST && ms != MaterialStack.EMPTY && ms.material().hasProperty(PropertyKey.BLAST)) {
you get the idea, there's more

2025-03-08 00:12 UTC, krossgg requested changes
I think there are places where you could be using `isEmpty()` for MaterialStack/TagPrefixes so double check those

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/VanillaRecipeHelper.java
> +        return new ItemMaterialInfo(materialStacksExploded.object2LongEntrySet().stream()
You don't need to sort this here, the constructor sorts it anyways. It might also be preferable to make a new `ItemMaterialInfo` constructor that takes an `Object2LongMap<Material>` and iterates over its entries itself, rather than doing it here so that the stream can be avoided.

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +        if (materialEntry == null) {
Honestly I would prefer you use a static boolean to denote that the map hasn't been resolved yet, rather than hinging on the fact that the default return value being null.
Dealer's choice.

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +        return matEntry;
```suggestion
        return TAG_MATERIAL_ENTRY.getOrDefault(tag, MaterialEntry.NULL_ENTRY);
```

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +        Map<ItemStack, ItemMaterialInfo> f = new HashMap<>();
This should use the custom hash strategy so that the amount in the ItemStack doesn't matter

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +        return mat;
```suggestion
        return FLUID_MATERIAL.getOrDefault(fluid, GTMaterials.NULL);
```

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/ItemMaterialInfo.java
> +        materialStacks.forEach(stack -> materials.addTo(stack.material(), stack.amount()));
Can you replace this with a for-each like on line 20 for consistency

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/ItemMaterialInfo.java
> +        return sortedMaterials.hashCode();
I'm not sure how often you need the hash of this class, but it could be wise to precompute and store it at the end of `setSortedMaterials`
if you do end up doing this, remember to also add `this.hashCode == that.hashCode` in your `equals()` method as a fail-fast condition

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +    public GTRecipeBuilder inputItems(TagPrefix tagPrefix, @Nullable Material material, int count) {
Why is the Material nullable when nobody should be passing in a null material? You don't want to deal with null materials so just set it `@NotNull` to establish the contract

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +    public GTRecipeBuilder outputItems(TagPrefix orePrefix, @Nullable Material material, int count) {
Ditto

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +        var itemInputs = input.get(ItemRecipeCapability.CAP);
Should probably be `getOrDefault`s for safety

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +            if (out != null && out != ItemStack.EMPTY.getItem() && outputCount != 0 && !tempItemStacks.isEmpty())
Add brackets

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +
Early return if out == null

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +                var matList = matStacks.reference2LongEntrySet().stream()
Ditto about using a constructor that takes a map in `ItemMaterialInfo`

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +                ItemMaterialData.UNRESOLVED_ITEM_MATERIAL_INFO.remove(new ItemStack(out, outputCount));
add brackets

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +
early return if out == null

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/DecompositionRecipeHandler.java
> +            List<Long> materialAmounts = new ArrayList<>();
Use LongList and LongStream

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/DecompositionRecipeHandler.java
> +                    .duration(((int) material.getProtons() * (int) totalInputAmount * 2))
Do the entire calculation as a long, then saturated cast it to an int

2025-03-08 00:12 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/DecompositionRecipeHandler.java
> +            builder.inputItems(decomposePrefix, material, (int) totalInputAmount);
Saturated cast

2025-03-16 17:02 UTC, omergunr100 requested changes
Apart from annotating the utility class it looks good (assuming you gave it a test in-game)

2025-03-16 17:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
>  public class ChemicalHelper {
annotate with `@ParametersAreNonnullByDefault` and `@MethodsReturnNonnullByDefault`.

2025-03-16 17:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +    public static MaterialStack getMaterialStack(Object object) {
annotate parameter with `@Nullable`.

2025-03-16 17:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +        if (itemLike == null) return TagPrefix.NULL_PREFIX;
Remove null handling, this shouldn't be null from what I can tell.

2025-03-16 17:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +    public static Block getBlock(MaterialEntry materialEntry) {
Mark result nullable.

2025-03-16 17:02 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
>      public static Block getBlock(TagPrefix orePrefix, Material material) {
Mark result nullable.

2025-03-18 10:31 UTC, omergunr100 approved these changes

2025-03-19 06:05 UTC, Ghostipedia requested changes

2025-03-19 06:05 UTC, Ghostipedia commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/ItemMaterialInfo.java
>          ItemMaterialInfo that = (ItemMaterialInfo) o;
Nitpick, this is a horrible name. Ideally call it 'other' or give it a better param than just "O"

2025-03-19 06:05 UTC, Ghostipedia commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/MaterialStack.java
>      @Override
use instanceof instead of o.getClass()

2025-03-19 06:05 UTC, Ghostipedia commented on src/main/java/com/gregtechceu/gtceu/client/renderer/BlockHighlightRenderer.java
> +        buffer.vertex(mat, from.x, from.y, from.z)
Cherrypick out

2025-03-19 06:05 UTC, Ghostipedia commented on src/main/java/com/gregtechceu/gtceu/data/recipe/misc/MachineRecipeLoader.java
>                  .duration(100).EUt(16)
Remove (Check Internal)

2025-03-19 09:32 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/ItemMaterialInfo.java
>          ItemMaterialInfo that = (ItemMaterialInfo) o;
this is the intellij generated equals method

2025-03-20 02:59 UTC, krossgg requested changes

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/block/PipeBlock.java
> +                    .get(TagPrefix.frameGt, pipeNode.getFrameMaterial())
spotlessJava lol

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +        } else if (object instanceof Ingredient ing) {
Why do you check specifically for a SizedIngredient here?

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +            if (entryMaterial != GTMaterials.NULL) {
This is already satisfied by `!entry.isEmpty()` no?

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +            return MaterialStack.EMPTY;
Brackets or one-line

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
>          return info.getMaterial().copy();
Do we even need to copy since MaterialStack is immutable

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +        return materialEntry;
This `if` is unnecessary, as `materialEntry.isEmpty() => materialEntry == NULL_ENTRY`, so you can just return `materialEntry`

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +                return new ArrayList<>(List.of(prefix.getItemFromTable(entry.material())));
`new ArrayList<>(List.of())` ...

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
> +        if (materialEntry.material() == GTMaterials.NULL) return new ArrayList<>();
```suggestion
        if (materialEntry.isEmpty()) return Collections.emptyList();
```

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/ChemicalHelper.java
>                  .map(Map.Entry::getValue).findFirst();
Can you put linebreaks between each method call after `.stream()`

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +    public static final Map<MaterialEntry, ArrayList<Supplier<? extends Block>>> MATERIAL_ENTRY_BLOCK_MAP = new Object2ObjectOpenHashMap<>();
Polymorphism - the value type should be `List<Supplier<? extends X>>`

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +    public static final Map<Supplier<BlockState>, TagPrefix> ORES_INVERSE = new Object2ObjectOpenHashMap<>();
You use `containsValue` and we use static const instances of `TagPrefix`, so make this map an `Object2ReferenceOpenHashmap<>();`

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +        ITEM_MATERIAL_INFO.put(item, materialInfo);
put this into an `else` block and then remove `return` from each branch.

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +        ITEM_MATERIAL_INFO.remove(item);
Put this into `else` block, remove returns

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +        if (materialEntry.material() != GTMaterials.NULL) {
```suggestion
        if (!materialEntry.isEmpty()) {
```

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +    public static void registerMaterialInfoItems(TagPrefix tagPrefix, @Nullable Material material,
`material` probably shouldn't be `@Nullable`

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +    public static void registerMaterialInfoItems(TagPrefix tagPrefix, @Nullable Material material, ItemLike... items) {
Ditto

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +            if (item instanceof Block block) {
Since you're already going to loop over the items, you might as well not do the `Arrays.asList` call.
```suggestion
        var entryList = MATERIAL_ENTRY_ITEM_MAP.computeIfAbsent(materialEntry, entry -> new ArrayList<>());
        for (Supplier<? extends ItemLike> item : items) {
            ITEM_MATERIAL_ENTRY.add(Pair.of(item, materialEntry));
            entryList.add(item);
            if (item instanceof Block block) {
```

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +                continue;
Brackets or one-line

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +            var count = entry.getKey().getCount();
Pull `entry.getKey()` to a var up here

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java
> +                    ITEM_MATERIAL_INFO.get(entry.getKey().getItem()).getMaterials(), false, null);
`ITEM_MATERIAL_INFO.get(entry.getKey().getItem())` isn't this just `matInfo` from above? In the true branch just set `matInfo = new ItemMaterialInfo(stacks)` then put it in the map.

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/HazardProperty.java
> +            if (!entry.isEmpty() && entry.material() != GTMaterials.NULL) {
`material` can't be null if `entry` isn't empty, as the NULL material is only associated with the NULL entry. Unless there is some weird edge case. In which case, add `material != GTMaterials.NULL` to `MaterialEntry#isEmpty`.

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/MaterialEntry.java
> +
Arguably this could be memoized for every pair of TagPrefix, Material instead of creating a new `MaterialEntry` every time. Utils has a BiFunction memoize as well. Up to you if you want to implement this.

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/MaterialStack.java
>      public MaterialStack copy() {
I think this copy method and whatever calls it just isn't needed - the record is immutable so it's not necessary to copy it.

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/gui/misc/ProspectorMode.java
> +                                if (!entry.isEmpty() && entry.material() != GTMaterials.NULL) {
ditto on NULL mat

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/item/IGTTool.java
> +        if (entry.isEmpty() || entry.material() == GTMaterials.NULL) return false;
Ditto on NULL mat

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/pattern/Predicates.java
> +                Arrays.stream(frameMaterials).map(m -> GTMaterialBlocks.MATERIAL_BLOCKS.get(TagPrefix.frameGt, m))
Move `Arrays.stream()` onto the previous line and put line breaks between stream methods

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/client/TooltipsHandler.java
> +        if (!materialEntry.isEmpty() && materialEntry.material() != GTMaterials.NULL) {
Ditto NULL mat

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/client/TooltipsHandler.java
> +            if (materialEntry.material().getChemicalFormula() != null &&
Just pull out `materialEntry.material().getChemicalFormula()` into a var

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/block/CableBlock.java
> +                    .get(TagPrefix.frameGt, pipeNode.getFrameMaterial())
spotlessJava lol

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/block/FluidPipeBlock.java
> +                    .get(TagPrefix.frameGt, pipeNode.getFrameMaterial())
spotlessJava lol

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/machine/steam/SteamSolidBoilerMachine.java
> +        if (materialStack.isEmpty())
Brackets or one-line

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +                }
Why do you only check for maxChance when you add it to the `List<ItemStack>`?

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +            GTCEu.LOGGER.error("Unification Entry material is null, id: {}, TagPrefix: {}", id, input.tagPrefix());
Change log to `Material Entry`

2025-03-20 02:59 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +        return inputItems(input.tagPrefix(), input.material(), 1);
Send this through the `inputItems(input, 1)` overload

2025-03-20 09:37 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java
> +                }
chanced inputs should not contribute towards decomp

2025-03-20 09:43 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/common/machine/steam/SteamSolidBoilerMachine.java
> +        if (materialStack.isEmpty())
fixed but side note the `return GTValues.RNG.nextFloat() <= remainderChance ? remainder : ItemStack.EMPTY;` never gets hit because of that if else chain

2025-03-20 11:35 UTC, omergunr100 commented
Did you know you can hook underwater for extra speed?

2025-03-21 01:47 UTC, krossgg requested changes

2025-03-21 01:47 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/stack/MaterialStack.java
>      public MaterialStack copy() {
Remove this `copy` and calls as well - again, object is immutable; its OK to pass around the same reference.

2025-03-21 01:47 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/client/TooltipsHandler.java
>          if (material != null) {
Can't be null. (Do you even look at IntellJ's static analysis?) 
![image](https://github.com/user-attachments/assets/74d210a1-e3e3-426e-9289-4bf98844c1b8)

2025-03-21 01:47 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/block/CableBlock.java
> +                    .get(TagPrefix.frameGt, pipeNode.getFrameMaterial()).getDefaultState();
I wanted you to just remove the linebreak after `MATERIAL_BLOCKS` on these - keep the linebreak after the first `.get`

2025-03-21 01:47 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/common/block/FluidPipeBlock.java
> +                    .get(TagPrefix.frameGt, pipeNode.getFrameMaterial()).getDefaultState();
Ditto

2025-03-21 22:58 UTC, krossgg requested changes, later dismissed
You should mark some of the things you removed `Nullable` from as `NotNull` potentially - check context and decide.
Also check these:
`GeodeVeinGenerator.java:300`
`StoneTypeEntry.java:229`

2025-03-21 22:58 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/integration/kjs/builders/block/CoilBlockBuilder.java
> +    public transient Supplier<Material> material = () -> null;
... you forgot to change the default supplier
```suggestion
    public transient Supplier<Material> material = () -> GTMaterials.NULL;
```

2025-03-21 22:58 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/blockentity/PipeBlockEntity.java
> +    private Material frameMaterial = GTMaterials.NULL;
```suggestion
	@NotNull
    private Material frameMaterial = GTMaterials.NULL;
```

2025-03-21 22:58 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/misc/RecyclingRecipes.java
> +                if (!entry.isEmpty() && inputStack != null) {
inputStack can't be null (please look at your IntelliJ warnings. I beg)

2025-03-24 18:28 UTC, Spicierspace153 reviewed
please fix merge conflicts and remember that hooks can give a speed boost underwater

2025-03-25 22:09 UTC, omergunr100 requested changes
Add `isNull()` to `Material` that just compares the material to the null material, there's so many `<material> [=!]= GTMaterials.NULL`.

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/HazardProperty.java
>          }
Remove this clause, it just clutters the code, getting the property from the map is O(1) and the material won't be null anymore, and shouldn't be the null material most of the time, so it doesn't really save us anything.

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/IngotProperty.java
> +    private Material macerateInto = GTMaterials.NULL;
Mark as not null

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/IngotProperty.java
> +    private Material magneticMaterial = GTMaterials.NULL;
Mark as not null

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/IngotProperty.java
> +    private Material arcSmeltingInto = GTMaterials.NULL;
Mark as not null

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/IngotProperty.java
> +    private Material smeltingInto = GTMaterials.NULL;
Mark as not null

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/IngotProperty.java
> +        if (arcSmeltingInto == GTMaterials.NULL || arcSmeltingInto == null) arcSmeltingInto = properties.getMaterial();
Should be `arcSmeltingInto == GTMaterials.NULL`

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/IngotProperty.java
> +        if (macerateInto == GTMaterials.NULL || macerateInto == null) macerateInto = properties.getMaterial();
Should be `macerateInto == GTMaterials.NULL`

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/IngotProperty.java
> +        if (magneticMaterial != GTMaterials.NULL && magneticMaterial != null)
Remove `magneticMaterial != null` it'll never be null

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/OreProperty.java
> +    private Material directSmeltResult = GTMaterials.NULL;
Mark as not null

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/OreProperty.java
> +    private Material washedIn = GTMaterials.NULL;
Mark as not null

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/OreProperty.java
> +        if (directSmeltResult != GTMaterials.NULL && directSmeltResult != null)
Remove `directSmeltResult != null` it'll never be null

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/OreProperty.java
> +        if (washedIn != GTMaterials.NULL && washedIn != null)
Remove `washedIn != null` it'll never be null

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/common/data/GTMaterials.java
> -    @Nullable
If it's not null don't just remove nullable mark it as not null

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/common/data/materials/ElementMaterials.java
> +                        GENERATE_SPRING_SMALL,
Huh?

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/common/data/materials/ElementMaterials.java
> +                        GENERATE_SPRING_SMALL,
Huh?

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/common/data/materials/FirstDegreeMaterials.java
> +                        GENERATE_FINE_WIRE)
Huh?

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/common/data/materials/FirstDegreeMaterials.java
> +                        GENERATE_FOIL,
Huh?

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/common/data/materials/HigherDegreeMaterials.java
> +                        GENERATE_FINE_WIRE,
Huh?

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/common/data/materials/SecondDegreeMaterials.java
> +                        DECOMPOSITION_BY_CENTRIFUGING)
Huh?

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/common/data/materials/SecondDegreeMaterials.java
> +                        DECOMPOSITION_BY_CENTRIFUGING)
Huh?

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/common/data/materials/SecondDegreeMaterials.java
> +                        DECOMPOSITION_BY_CENTRIFUGING)
Huh?

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/common/unification/material/MaterialRegistryImpl.java
> +    private Material fallbackMaterial = GTMaterials.NULL;
Mark as not null

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/integration/map/ftbchunks/veins/ore/OreVeinIcon.java
> +                return null;
Return the null material instead

2025-03-25 22:09 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/integration/map/ftbchunks/veins/ore/OreVeinIcon.java
>          Material firstMaterial = null;
Set it to the null material

2025-03-27 07:14 UTC, omergunr100 approved these changes
RIP yap-max pr, it wasn't good while it lasted o7

2025-03-27 07:16 UTC, Ghostipedia approved these changes

2025-03-27 07:28 UTC, merged