Improve TagPrefix-based Recipe Generation
GregTechCEu/GregTechCEu-1.19 pull request #2616
Opened 2024-12-21 21:47 UTC by TechLord22

## What
Improves TagPrefix-based Recipe Generation. Notably, this PR no longer iterates all materials for every registration handler. Instead, materials are only iterated once.

## Implementation Details
* Ports a very small part of GregTechCEu/GregTech#1712. This may cause some breakage, but addons should not have been using `GTUtil.copyAmount` and `GTUtil.selectItemInList` to begin with.
* Removes `TagPrefix.MaterialRecipeHandler` and `TagPrefix#executeHandler`. This will require addons to update, and this PR serves as an example of how to do so.
* Ports GregTechCEu/GregTech#2343.

## Outcome
Improves performance and cleans up recipe generation code.

2025-01-04 10:34 UTC, screret submitted a review, later dismissed

2025-01-04 10:34 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/OreProperty.java
> +    public void addOreByProducts(@NotNull Material @NotNull... materials) {
I love `@NotNull Material @NotNull...`

2025-01-04 10:34 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/utils/GTUtil.java
>      }
this can be removed in favor of `ItemStack#copyWithCount`

2025-01-04 10:34 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/utils/GTUtil.java
> +                return copy;
change this to use `ItemStack#copyWithCount`

2025-01-04 10:34 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/WireRecipeHandler.java
> +    }
could use the `Util.make(T,Consumer<T>)` method from vanilla here

2025-02-21 05:56 UTC, Spicierspace153 approved these changes

2025-03-04 20:43 UTC, krossgg requested changes

2025-03-04 20:43 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/RecyclingRecipeHandler.java
>      private static final List<Object> CRUSHING_PREFIXES = Arrays.asList(
Can we make this less ugly? Either make them all predicates using a helper method or hardcode all the matching tagPrefixes

2025-03-04 20:43 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/ToolRecipeHandler.java
> +    public static void setup() {
This can be done without a separate method call - either using `Util.make`, a static block, or using a constructor of `Int2RefArrayMap` - the call to `setup()` seems to be the first time the class is loaded so this would be equivalent behavior.

2025-03-04 20:43 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/WireCombiningHandler.java
> +                    new UnificationEntry(prefix, material),
Can this entry just be predefined instead of making a new one every time?

2025-03-04 20:43 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/data/recipe/misc/CustomToolRecipes.java
> +        batteryItems.put(GTValues.ULV, Collections.singletonList(GTItems.BATTERY_ULV_TANTALUM));
Just use `List#of` instead of Collections and Guava

2025-03-05 05:56 UTC, krossgg requested changes

2025-03-05 05:56 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/info/MaterialFlag.java
> +        Set<PropertyKey<?>> thisAndDeps = new HashSet<>(requiredProperties);
Use ObjectOpenHashSet

2025-03-05 05:56 UTC, krossgg commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/info/MaterialFlag.java
> +                .collect(Collectors.toSet()));
```suggestion
		requiredFlags.stream()
                .map(MaterialFlag::getAllRequiredProperties)
                .forEach(thisAndDeps::addAll)
```
Change the code in the method above to match this as well - no need to flatmap multiple streams or have an unnecessary collection

2025-03-05 06:09 UTC, krossgg approved these changes
Looks fine but would like another person to scrutinize.

2025-03-05 09:23 UTC, screret approved these changes
LGTM

2025-03-05 09:23 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/RecyclingRecipeHandler.java
>      private static final List<Object> CRUSHING_PREFIXES = Arrays.asList(
oh wait yeah do this.
make them all predicates, that'll be cleaner.

2025-03-05 09:27 UTC, screret submitted a review, later dismissed

2025-03-05 09:27 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/generated/RecyclingRecipeHandler.java
> +            pipeSmallRestrictive, pipeNormalRestrictive, pipeLargeRestrictive, pipeHugeRestrictive);
IMO this should be a set of predicates

2025-03-05 21:34 UTC, krossgg approved these changes

2025-03-25 22:53 UTC, omergunr100 reviewed
I don't see anything wrong with it rn, will need another look after the material refactor gets merged.

2025-03-27 09:31 UTC, omergunr100 requested changes

2025-03-27 09:31 UTC, omergunr100 commented on src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/properties/OreProperty.java
> +    public void setOreByProducts(@NotNull Collection<Material> materials) {
`@NotNull Collection<@NotNull Material> materials`

2025-03-27 09:35 UTC, omergunr100 approved these changes

2025-03-27 20:42 UTC, merged