Make setting crafting components from KJS more ergonomic.
GregTechCEu/GregTechCEu-1.19 pull request #2639
Opened 2024-12-25 06:07 UTC by tomprince

## What
Javascript objects only support strings as keys, so allow passing objects (i.e maps) with short tier names as keys for defining crafting components.

## Outcome
Before (note in particular the need to import `Map` from java, rather than native JS syntax):
```javascript
const Map = Java.loadClass("java.util.Map");

GTCEuStartupEvents.craftingComponents(event => {

    //Make LuV+ electrolyzer wires not osmium for funsies :)
    let wireElectricMap = {};
    event.modify(CraftingComponent.WIRE_ELECTRIC, Map.of(
        GTValues.LuV, UnificationEntry(TagPrefix.wireGtSingle, GTMaterials.VanadiumGallium),
        GTValues.ZPM, UnificationEntry(TagPrefix.wireGtSingle, GTMaterials.NaquadahAlloy),
        GTValues.UV, UnificationEntry(TagPrefix.wireGtSingle, GTMaterials.get('sculk_superconductor')),
        GTValues.UHV, UnificationEntry(TagPrefix.wireGtSingle, GTMaterials.get('activated_netherite')),
        GTValues.UEV, UnificationEntry(TagPrefix.wireGtSingle, GTMaterials.Holmium),
        GTValues.UIV, UnificationEntry(TagPrefix.wireGtSingle, GTMaterials.get('monium')),
    ));
})
```
After:
```javascript
GTCEuStartupEvents.craftingComponents(event => {

    //Make LuV+ electrolyzer wires not osmium for funsies :)
    event.modify(CraftingComponent.WIRE_ELECTRIC, {
        LuV: UnificationEntry(TagPrefix.wireGtSingle, GTMaterials.VanadiumGallium),
        ZPM: UnificationEntry(TagPrefix.wireGtSingle, GTMaterials.NaquadahAlloy),
        UV: UnificationEntry(TagPrefix.wireGtSingle, GTMaterials.get('sculk_superconductor')),
        UHV: UnificationEntry(TagPrefix.wireGtSingle, GTMaterials.get('activated_netherite')),
        UEV: UnificationEntry(TagPrefix.wireGtSingle, GTMaterials.Holmium),
        UIV: UnificationEntry(TagPrefix.wireGtSingle, GTMaterials.get('monium')),
    });
});
```

## Potential Compatibility Issues
The functions now accept maps with either numbers (as now) or strings (which can be from native javascript objects), so the change should be backwards compatible.

2024-12-25 06:08 UTC, tomprince commented
I want to have a look at improving the error handling somewhat, still.

2024-12-25 09:47 UTC, screret requested changes

2024-12-25 09:47 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/GTValues.java
> +    public static final Map<String, Integer> RVN = IntStream.range(0, VN.length)
Object2IntMap to avoid boxing?

2024-12-25 09:47 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/GTValues.java
> +    public static final Map<String, Integer> RVN = IntStream.range(0, VN.length)
Also, what does RVN stand for?

2024-12-25 10:43 UTC, Luexa commented on src/main/java/com/gregtechceu/gtceu/api/GTValues.java
> +    public static final Map<String, Integer> RVN = IntStream.range(0, VN.length)
Probably reverse voltage names, no?

2025-03-29 04:40 UTC, YoungOnionMC commented
resolved as part of #2713

2025-03-29 04:40 UTC, closed without merging