Sdev/javadocs
GregTechCEu/GregTechCEu-1.19 pull request #2674
Opened 2024-12-30 18:55 UTC by stanieldev

## What
This PR adds a bunch of JavaDocs for functions that previously didn't have them, were unclear, or were outdated.

## Implementation Details
When reviewing, I would look for my descriptions being proper, since some of them I had to figure out after reading the function's contents multiple times.

## Outcome
Hopefully the readability will increase and help with future development.

## Potential Compatibility Issues
I didn't change any variable names, instead leaving them as TODOs while I was working.
They can be removed in the future when they are either changed or rejected.

2024-12-30 19:00 UTC, Ghostipedia commented
SpotlessApply

2024-12-30 19:02 UTC, Ghostipedia requested changes
Looks Good, just run formatting and we can merge it 👍

2024-12-30 19:12 UTC, screret requested changes

2024-12-30 19:12 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/block/MaterialBlock.java
> +        // TODO: Avoid using arrow notation
>:(

2024-12-30 19:12 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/block/MaterialPipeBlock.java
> +        // TODO: Avoid Arrow Notation and use Early Returns
>:(

2025-01-04 09:48 UTC, screret requested changes

2025-01-04 09:48 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/block/MaterialPipeBlock.java
> +                    else if (pipe.isPainted()) {
this shouldn't be an else if, it should fall through to this if the frame material checks fail IMO.

2025-01-04 09:48 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/api/block/MaterialPipeBlock.java
> +                    else if (pipe.isPainted()) {
also, spotless.

2025-12-03 21:30 UTC, closed without merging