Various Nitpick Changes
GregTechCEu/GregTechCEu-1.19 pull request #2683
Opened 2024-12-31 07:11 UTC by YoungOnionMC

## What
Fixes #309 

## Implementation Details
adding tags, removing tags, adding recipes etc

## Outcome
1 less old pr

2024-12-31 07:12 UTC, Spicierspace153 approved these changes
it looks good from a code perspective but ghost should check the recipes for balance

2024-12-31 08:38 UTC, screret requested changes, later dismissed

2024-12-31 08:38 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/GTBlocks.java
> +        }
this won't work for removing the pickaxe tags as it's only applied when you run datagen.

2024-12-31 08:38 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/GTBlocks.java
> +        }
this won't work for removing the pickaxe tags as it's only applied when you run datagen.

2024-12-31 08:38 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/GTBlocks.java
> +        }
this won't work for removing the pickaxe tags as it's only applied when you run datagen.

2024-12-31 08:38 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/GTBlocks.java
> +        }
this won't work for removing the pickaxe tags as it's only applied when you run datagen.

2024-12-31 08:38 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/GTBlocks.java
> +        }
this won't work for removing the pickaxe tags as it's only applied when you run datagen.

2024-12-31 08:38 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/GTBlocks.java
> +        }
this won't work for removing the pickaxe tags as it's only applied when you run datagen.

2024-12-31 08:38 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/GTBlocks.java
> +        }
this won't work for removing the pickaxe tags as it's only applied when you run datagen.

2024-12-31 08:38 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/GTBlocks.java
> +        }
this won't work for removing the pickaxe tags as it's only applied when you run datagen.

2024-12-31 08:38 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/GTBlocks.java
> +        }
this won't work for removing the pickaxe tags as it's only applied when you run datagen.

2024-12-31 08:38 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/data/GTBlocks.java
> +        }
this won't work for removing the pickaxe tags as it's only applied when you run datagen.

2024-12-31 08:38 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/lang/BlockLang.java
> +        replace(provider, "block.gtceu.steel_turbine_casing", "Magnalium Turbine Casing");
no, not doing this

2024-12-31 08:38 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/data/recipe/misc/MachineRecipeLoader.java
> +                .save(provider);
tell the guy to just use AE2. or something. these are useless.

2025-03-01 08:21 UTC, YoungOnionMC commented on src/main/java/com/gregtechceu/gtceu/data/lang/BlockLang.java
> +        replace(provider, "block.gtceu.steel_turbine_casing", "Magnalium Turbine Casing");
ghost said the magnalium casing naming was fine, resolving

2025-03-04 01:36 UTC, krossgg approved these changes

2025-03-29 03:28 UTC, Ghostipedia approved these changes

2025-03-29 03:40 UTC, merged