ITEM PIPES
GregTechCEu/GregTechCEu-1.19 pull request #437
Opened 2023-10-01 20:45 UTC by screret

gotta fix a couple bugs & test first.

2023-10-02 19:04 UTC, screret commented
bugs have been fixed

2023-10-03 20:23 UTC, mikerooni requested changes

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/api/pipenet/longdistance/LongDistancePipeBlock.java
> +        }
This might benefit from extracting it into a seaparate method.

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/api/pipenet/longdistance/LongDistancePipeType.java
> +     * @return The minimum required distance (not pipe count between endpoints) between to endpoints to work.
```suggestion
     * @return The minimum required distance (not pipe count) between two endpoints to work.
```

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/api/pipenet/longdistance/NetworkBuilder.java
> +            } else {
consider short circuiting the loop via `continue` instead of an `else` branch

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java
> +            if (defaultHandler.getNet() != current) {
consider early returns instead of the nested ifs, for easier readability

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java
> +        if (level != null) {
early return might be better here as well

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java
> +            ItemPipeNet currentFluidPipeNet = this.currentItemPipeNet.get();
**[REQUIRED]**  
Wrong variable names. Should be `itemPipeBlock` and `currentItemPipeNet` instead of fluid.

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java
> +        if (++timer % 20 == 0) {
**[REQUIRED]**  
If possible, please consider using `PipeBlockEntity#getOffsetTimer()` instead, so that the load is distributed evenly across ticks.

In case this isn't possible (e.g. if all pipe block entities on the same pipe net need to update in the same tick), it may be possible to add a random offset to each pipenet instead.

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/common/cover/ConveyorCover.java
> +    @Getter
```suggestion
    @Persisted @DescSynced @Getter
```

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/common/cover/ConveyorCover.java
> +            group.addWidget(distributionModeButton);
```suggestion
            group.addWidget(new EnumSelectorWidget<>(149, 166, 20, 20,
                    DistributionMode.VALUES, DistributionMode.INSERT_FIRST,
                    this::setDistributionMode));
```

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/common/cover/ItemFilterCover.java
> +    @Getter
```suggestion
    @Persisted @DescSynced @Getter
```

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java
> +                    tooltip.add(Component.translatable("gtceu.machine.endpoint.tooltip.min_length", ConfigHolder.INSTANCE.machines.ldItemPipeMinDistance));
**[REQUIRED]**  
This should use the config option `ldFluidPipeMinDistance` instead of the one for item pipes

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/common/machine/storage/LongDistanceEndpointMachine.java
> +    @Getter @Setter
```suggestion
    @Persisted @Getter @Setter
```

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/data/lang/LangHandler.java
> +        provider.add("gtceu.machine.endpoint.tooltip.3", "Only pipeline endpoints need to be §fchunk-loaded§7.");
**[REQUIRED]**  
Please use `multiLang()` here instead.

2023-10-03 20:23 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java
> +    }
Consider using `@Getter` instead

2023-10-03 20:25 UTC, mikerooni commented
The review comments marked with **[REQUIRED]** are necessary, all others are just (optional) suggestions for code quality ^^

2023-10-04 06:48 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java
> +        if (++timer % 20 == 0) {
I don't think a simple modulo operation + assignment needs that TBH.

2023-10-04 13:33 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java
> +        if (++timer % 20 == 0) {
True. If this method does more at some point, we can always do that later.

2023-10-04 13:59 UTC, mikerooni approved these changes
lgtm

2023-10-04 14:07 UTC, merged