ME i/o hatches for multiblocks
GregTechCEu/GregTechCEu-1.19 pull request #500
Opened 2023-10-29 14:48 UTC by screret

Pattern-providing ones _might_ come in a separate PR.

2023-11-02 19:43 UTC, screret commented
oh fuck, merge conflicts spawned

2023-11-02 20:14 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/integration/ae2/gui/widget/AEConfigWidget.java
> +    protected final boolean areAEStackCountEquals(GenericStack s1, GenericStack s2) {
Small typo: should be `areAEStackCountsEqual`

2023-11-02 20:40 UTC, mikerooni requested changes

2023-11-02 20:40 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEInputBusPartMachine.java
> +            if (this.updateMEStatus()) {
I'd use two early returns here, to reduce nesting depth

2023-11-02 20:40 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEInputHatchPartMachine.java
> +            if (this.updateMEStatus()) {
Early returns would be good here as well

2023-11-02 20:40 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEOutputBusPartMachine.java
> +            if (this.updateMEStatus()) {
Here as well

2023-11-02 20:40 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEOutputHatchPartMachine.java
> +            if (this.updateMEStatus()) {
And here as well

2023-11-03 14:35 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/integration/ae2/util/AEFluidConfigSlot.java
> +    public void drawInBackground(@NotNull GuiGraphics graphics, int mouseX, int mouseY, float partialTicks) {
Might be able to extract some parts of this into `AEConfigSlot` (optional)

2023-11-03 16:06 UTC, mikerooni approved these changes

2023-11-03 16:06 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/integration/ae2/util/AEFluidConfigSlot.java
> +        if (fluidTank.getFluidAmount() > 0) {
might be better to early return here

2023-11-03 16:07 UTC, merged