Fix steam boiler can accept steam
GregTechCEu/GregTechCEu-1.19 pull request #518
Opened 2023-11-05 04:36 UTC by Phoupraw

2023-11-11 20:58 UTC, Phoupraw reviewed
It makes no sense that this commit appears here. It should have been merged in #285.

2023-11-18 21:10 UTC, mikerooni commented
Includes #291 - that one can be closed when this PR is merged.

2023-11-20 03:31 UTC, Yefancy requested changes, later dismissed

2023-11-20 03:31 UTC, Yefancy commented on common/src/main/java/com/gregtechceu/gtceu/api/machine/trait/NotifiableFluidTank.java
> +        if (resource.isEmpty() || !getCapabilityIO().support(IO.IN)) return 0;
use `canCapInput()` instead

2023-11-20 03:32 UTC, Yefancy commented
lgtm

2023-11-21 19:26 UTC, mikerooni approved these changes

2023-11-22 22:14 UTC, Phoupraw commented
How can I resolve outdated requested change?

2023-11-24 12:33 UTC, merged