Port GregTechCEu/GregTech#2132
GregTechCEu/GregTechCEu-1.19 pull request #521
Opened 2023-11-05 18:00 UTC by mikerooni

2023-11-05 18:01 UTC, mikerooni commented
This currently runs into an issue where networks don't have all endpoints registered

2023-11-11 13:32 UTC, screret requested changes

2023-11-11 13:32 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/api/pipenet/longdistance/ILDNetworkPart.java
> +        return blockState instanceof ILDNetworkPart part ? part : ILDEndpoint.tryGet(level, pos);
This should probably be `blockState.getBlock()`?

2023-11-11 15:07 UTC, mikerooni commented on common/src/main/java/com/gregtechceu/gtceu/api/pipenet/longdistance/ILDNetworkPart.java
> +        return blockState instanceof ILDNetworkPart part ? part : ILDEndpoint.tryGet(level, pos);
Yes. Yes, indeed.

2024-01-30 16:19 UTC, closed without merging