Solar Panels (Restored)
GregTechCEu/GregTechCEu-1.19 pull request #564
Opened 2023-11-20 09:52 UTC by poggers16

#551 restored :3

2023-11-20 14:15 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/api/cover/CoverBehavior.java
> +import java.security.DrbgParameters;
tf?

2023-11-20 14:17 UTC, screret requested changes

2023-11-20 14:17 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/utils/GTUtil.java
> +import net.minecraft.core.BlockPos;
tf are these imports?

2023-11-20 14:17 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/api/cover/CoverBehavior.java
> +import java.security.DrbgParameters;
same here

2023-11-21 13:00 UTC, poggers16 commented on common/src/main/java/com/gregtechceu/gtceu/api/cover/CoverBehavior.java
> +import java.security.DrbgParameters;
removed all of those

2023-11-21 13:01 UTC, poggers16 commented on common/src/main/java/com/gregtechceu/gtceu/utils/GTUtil.java
> +import net.minecraft.core.BlockPos;
removed those imports 🥺

2023-11-21 14:51 UTC, screret approved these changes
don't merge for this update, but next one.

2023-11-24 11:21 UTC, merged