Rewrite `GTEmiOreProcessing`
GregTechCEu/GregTechCEu-1.19 pull request #599
Opened 2023-11-30 10:47 UTC by Phoupraw

The original `GTEmiOreProcessing` doesn't go well with EMI. It lacks many classical features of EMI.

2023-11-30 10:57 UTC, screret requested changes

2023-11-30 10:57 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/integration/emi/oreprocessing/GTEmiOreProcessing.java
just replace the original... this is not a part of API.

2023-11-30 10:57 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/integration/emi/oreprocessing/GTEmiOreProcessingV2.java
though, WTF?? why not just use our systems instead of whatever this is, a separate thing??

2023-11-30 11:05 UTC, Arborsm commented on common/src/main/java/com/gregtechceu/gtceu/integration/emi/oreprocessing/GTEmiOreProcessingV2.java
haha, maybe the LDlib has too many issues on EMI

2023-11-30 11:26 UTC, Phoupraw commented on common/src/main/java/com/gregtechceu/gtceu/integration/emi/oreprocessing/GTEmiOreProcessingV2.java
There are several bugs in the original `GTEmiOreProcessing`:

1. Right click (look up usages) and left click (look up recipes) doesn't work.
2. EMI hotkeys, such as favorite, look up usages, look up recipes, and so on, doesn't work.
3. It shouldn't support crafting tree and should hide from craftable.
4. Only stone ore can be used to look up the processing graph, while other stone types of ores can't.
5. It can't be looked up by crushed ores and dust.
6. Fluid widget shows incorrect amount in fabric.
7. Results of sifter recipes shows incorrect chance and boost per tier.
8. Even if one ore doesn't have corresponding chemical bath recipe, you can still look it up by chemical bath machines. So do furnace, sifter and electromagnetic separator.
9. Its z is weird. The tooltip of slots is rendered under EMI widgets.
10. Its outputs contain items from other mod (like Tech Reborn).

It lacks some classical EMI features:

1. It doesn't have recipe ID.
2. It can't be favorited.
3. Chanced output doesn't use EMI's chance, which means it can't be rendered specially.
4. Multi-items slot doesn't show its content in tooltip.
5. Multi-items slot doesn't render special icon in its corner.

It's needed to write a special `GTOreProcessingWidget` or `GTEmiOreProcessing` for EMI.

2023-11-30 11:46 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/integration/emi/oreprocessing/GTEmiOreProcessingV2.java
you could've very well fixed those issues WITHOUT doing all that unnecessary extra work.

2023-11-30 12:10 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/integration/emi/oreprocessing/GTEmiOreProcessingV2.java
there are things in LDLib to do all of those. the rest can be done in the original widget class.

2023-12-09 15:25 UTC, Yefancy commented
I thought at first that ldlib had a ton of emi bugs, but I've found that the majority of the problems are due to the fact that the oreprecessingwidget isn't implemented correctly.

ldlib's emi plugin just needs to fix tooltips and add non-consumption support

2023-12-09 15:28 UTC, Yefancy commented
I'm happy or sad when I know because the problem is so simple to solve. and I've been getting a lot of complaints lately but most of them are just a tech issue.

2023-12-09 17:29 UTC, Arborsm commented
> I'm happy or sad when I know because the problem is so simple to solve. and I've been getting a lot of complaints lately but most of them are just a tech issue.

And adding things to the machine is not supported.

2023-12-09 17:33 UTC, Yefancy commented
> > I'm happy or sad when I know because the problem is so simple to solve. and I've been getting a lot of complaints lately but most of them are just a tech issue.
> 
> And adding things to the machine is not supported.

wdym

2023-12-09 17:35 UTC, Arborsm commented
> > > I'm happy or sad when I know because the problem is so simple to solve. and I've been getting a lot of complaints lately but most of them are just a tech issue.
> > 
> > 
> > And adding things to the machine is not supported.
> 
> wdym

on machine page -> the `+` on some recipe

2023-12-09 17:37 UTC, Arborsm commented
> > > I'm happy or sad when I know because the problem is so simple to solve. and I've been getting a lot of complaints lately but most of them are just a tech issue.
> > 
> > 
> > And adding things to the machine is not supported.
> 
> wdym

![image](https://github.com/GregTechCEu/GregTech-Modern/assets/44860537/b82dc6e7-b6f1-4ab0-8816-69c7a2a9dba1)

2023-12-09 17:38 UTC, Yefancy commented
yeah i know. you should say ae2 pattern importing

2023-12-09 17:40 UTC, Arborsm commented
> yeah i know. you should say ae2 pattern importing
hm, both

2023-12-09 17:44 UTC, Yefancy commented
well, i can't add ae2 supports for emi. bc ae2 doesn;t support emi so far.

and ldlib is using emi api (not jei -> emi)

2023-12-09 18:02 UTC, Arborsm commented
> well, i can't add ae2 supports for emi. bc ae2 doesn;t support emi so far.
> 
> and ldlib is using emi api (not jei -> emi)
> 
> https://github.com/AppliedEnergistics/Applied-Energistics-2/tree/main/src/main/java/appeng/integration/modules report to ae2 if you want such feature

emm,emi + jei support it,just fix the machine importing on EMI should make it work

2023-12-09 18:08 UTC, Yefancy commented
> > well, i can't add ae2 supports for emi. bc ae2 doesn;t support emi so far.
> > and ldlib is using emi api (not jei -> emi)
> > https://github.com/AppliedEnergistics/Applied-Energistics-2/tree/main/src/main/java/appeng/integration/modules report to ae2 if you want such feature
> 
> emm,emi + jei support it,just fix the machine importing on EMI should make it work

`the machine importing on EMI` IS NOT A BUG!! but a feature we havent added for gtm so far.
and it wont make the ae2 happy as well.

2023-12-10 07:37 UTC, Yefancy commented
#620

2023-12-10 07:37 UTC, closed without merging