Add solar boiler
GregTechCEu/GregTechCEu-1.19 pull request #701
Opened 2024-01-06 19:24 UTC by Xavier00014

Works like they did in 1.12

2024-01-06 21:10 UTC, screret requested changes, later dismissed

2024-01-06 21:10 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/common/machine/steam/SteamSolarBoiler.java
> +    public Direction getFrontFacing() { return Direction.UP; }
proper formatting please, no one liners.

2024-01-06 21:10 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/common/machine/steam/SteamSolarBoiler.java
> +    protected int getCooldownInterval() { return isHighPressure ? 50 : 45; }
same here.

2024-01-06 21:10 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/common/machine/steam/SteamSolarBoiler.java
> +    protected int getCoolDownRate() { return 3; }
and here.

2024-01-06 21:10 UTC, screret commented on common/src/main/java/com/gregtechceu/gtceu/common/machine/steam/SteamSolarBoiler.java
> +    protected void randomDisplayTick(RandomSource random, float x, float y, float z) { }
aand here.

2024-01-08 02:06 UTC, mikerooni approved these changes

2024-01-08 07:05 UTC, merged