API refinement
GregTechCEu/GregTechCEu-1.19 pull request #750
Opened 2024-01-14 15:11 UTC by screret

mostly lots of material changes, though this does also change how highTier is accessed and some other stuff

2024-01-15 07:01 UTC, mikerooni requested changes

2024-01-15 07:01 UTC, mikerooni commented on src/main/java/com/gregtechceu/gtceu/common/data/GTCovers.java
>      public static final int[] ALL_TIERS_WITH_ULV = new int[] {GTValues.ULV, GTValues.LV, GTValues.MV, GTValues.HV, GTValues.EV, GTValues.IV, GTValues.LuV, GTValues.ZPM, GTValues.UV};
It would be good to use `tiersBetween()` here as well:

```suggestion
    public static final int[] ALL_TIERS_WITH_ULV = GTValues.tiersBetween(GTValues.ULV, GTValues.UV);
```


Alternatively, if it should account for high-tier content:

```suggestion
    public static final int[] ALL_TIERS_WITH_ULV = GTValues.tiersBetween(GTValues.ULV, GTCEuAPI.isHighTier() ? GTValues.OpV : GTValues.UV);
```

2024-01-15 07:01 UTC, mikerooni commented on src/main/java/com/gregtechceu/gtceu/common/unification/material/MaterialRegistryImpl.java
> +    private final java.lang.String modid;
```suggestion
    private final String modid;
```

2024-01-15 07:01 UTC, mikerooni commented on src/main/java/com/gregtechceu/gtceu/forge/AlloyBlastPropertyAddition.java
> +        property.setRecipeProducer(new CustomAlloyBlastRecipeProducer(-1, -1, 16));
```suggestion
        GTMaterials.NiobiumNitride.getProperty(PropertyKey.ALLOY_BLAST)
                .setRecipeProducer(new CustomAlloyBlastRecipeProducer(1, 11, -1));

        GTMaterials.IndiumTinBariumTitaniumCuprate.getProperty(PropertyKey.ALLOY_BLAST)
                .setRecipeProducer(new CustomAlloyBlastRecipeProducer(-1, -1, 16));
```

2024-01-15 07:01 UTC, mikerooni commented on src/main/java/com/gregtechceu/gtceu/integration/kjs/GTRegistryInfo.java
> +    public static final MaterialRegistry KJS_MATERIAL_REGISTRY = GTCEuAPI.materialManager.createRegistry(KubeJS.MOD_ID);
Wouldn't this cause custom materials to be removed in existing worlds?

2024-01-15 07:08 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/common/unification/material/MaterialRegistryImpl.java
> +    private final java.lang.String modid;
the import disagreed with that.

2024-01-15 07:09 UTC, screret commented on src/main/java/com/gregtechceu/gtceu/integration/kjs/GTRegistryInfo.java
> +    public static final MaterialRegistry KJS_MATERIAL_REGISTRY = GTCEuAPI.materialManager.createRegistry(KubeJS.MOD_ID);
oh uh yeah true

2024-01-15 07:09 UTC, mikerooni commented on src/main/java/com/gregtechceu/gtceu/common/unification/material/MaterialRegistryImpl.java
> +    private final java.lang.String modid;
Ugh that sounds... not so great - let's just keep it as is then ^^

2024-01-15 07:15 UTC, mikerooni approved these changes

2024-01-15 07:22 UTC, screret commented
breaking changes momentos

2024-01-15 07:22 UTC, merged

2024-01-28 07:24 UTC, Ghostipedia commented
This Api Refinement hurts my soul (Breaking Changes moment)

2024-01-28 07:24 UTC, YoungOnionMC commented
🗣️ 🔥